// Code generated by protoc-gen-go.
// source: HSAdminRefreshProtocol.proto
// DO NOT EDIT!

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
//  refresh admin acls request.
type RefreshAdminAclsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsRequestProto) Reset()                    { *m = RefreshAdminAclsRequestProto{} }
func (m *RefreshAdminAclsRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsRequestProto) ProtoMessage()               {}
func (*RefreshAdminAclsRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// *
// Response for refresh admin acls.
type RefreshAdminAclsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshAdminAclsResponseProto) Reset()                    { *m = RefreshAdminAclsResponseProto{} }
func (m *RefreshAdminAclsResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshAdminAclsResponseProto) ProtoMessage()               {}
func (*RefreshAdminAclsResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

// *
//  refresh loaded job cache request.
type RefreshLoadedJobCacheRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLoadedJobCacheRequestProto) Reset()         { *m = RefreshLoadedJobCacheRequestProto{} }
func (m *RefreshLoadedJobCacheRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLoadedJobCacheRequestProto) ProtoMessage()    {}
func (*RefreshLoadedJobCacheRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{2}
}

// *
// Response for refresh loaded job cache.
type RefreshLoadedJobCacheResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLoadedJobCacheResponseProto) Reset()         { *m = RefreshLoadedJobCacheResponseProto{} }
func (m *RefreshLoadedJobCacheResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLoadedJobCacheResponseProto) ProtoMessage()    {}
func (*RefreshLoadedJobCacheResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{3}
}

// *
//  refresh job retention settings request.
type RefreshJobRetentionSettingsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshJobRetentionSettingsRequestProto) Reset() {
	*m = RefreshJobRetentionSettingsRequestProto{}
}
func (m *RefreshJobRetentionSettingsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshJobRetentionSettingsRequestProto) ProtoMessage()    {}
func (*RefreshJobRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{4}
}

// *
// Response for refresh job retention.
type RefreshJobRetentionSettingsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshJobRetentionSettingsResponseProto) Reset() {
	*m = RefreshJobRetentionSettingsResponseProto{}
}
func (m *RefreshJobRetentionSettingsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshJobRetentionSettingsResponseProto) ProtoMessage()    {}
func (*RefreshJobRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{5}
}

//
//  refresh log retention request.
type RefreshLogRetentionSettingsRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLogRetentionSettingsRequestProto) Reset() {
	*m = RefreshLogRetentionSettingsRequestProto{}
}
func (m *RefreshLogRetentionSettingsRequestProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLogRetentionSettingsRequestProto) ProtoMessage()    {}
func (*RefreshLogRetentionSettingsRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{6}
}

// *
// Response for refresh log retention.
type RefreshLogRetentionSettingsResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshLogRetentionSettingsResponseProto) Reset() {
	*m = RefreshLogRetentionSettingsResponseProto{}
}
func (m *RefreshLogRetentionSettingsResponseProto) String() string { return proto.CompactTextString(m) }
func (*RefreshLogRetentionSettingsResponseProto) ProtoMessage()    {}
func (*RefreshLogRetentionSettingsResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{7}
}

func init() {
	proto.RegisterType((*RefreshAdminAclsRequestProto)(nil), "hadoop.mapreduce.RefreshAdminAclsRequestProto")
	proto.RegisterType((*RefreshAdminAclsResponseProto)(nil), "hadoop.mapreduce.RefreshAdminAclsResponseProto")
	proto.RegisterType((*RefreshLoadedJobCacheRequestProto)(nil), "hadoop.mapreduce.RefreshLoadedJobCacheRequestProto")
	proto.RegisterType((*RefreshLoadedJobCacheResponseProto)(nil), "hadoop.mapreduce.RefreshLoadedJobCacheResponseProto")
	proto.RegisterType((*RefreshJobRetentionSettingsRequestProto)(nil), "hadoop.mapreduce.RefreshJobRetentionSettingsRequestProto")
	proto.RegisterType((*RefreshJobRetentionSettingsResponseProto)(nil), "hadoop.mapreduce.RefreshJobRetentionSettingsResponseProto")
	proto.RegisterType((*RefreshLogRetentionSettingsRequestProto)(nil), "hadoop.mapreduce.RefreshLogRetentionSettingsRequestProto")
	proto.RegisterType((*RefreshLogRetentionSettingsResponseProto)(nil), "hadoop.mapreduce.RefreshLogRetentionSettingsResponseProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for HSAdminRefreshProtocolService service

type HSAdminRefreshProtocolServiceClient interface {
	// *
	// Refresh admin acls
	RefreshAdminAcls(ctx context.Context, in *RefreshAdminAclsRequestProto, opts ...grpc.CallOption) (*RefreshAdminAclsResponseProto, error)
	// *
	// Refresh loaded job cache
	RefreshLoadedJobCache(ctx context.Context, in *RefreshLoadedJobCacheRequestProto, opts ...grpc.CallOption) (*RefreshLoadedJobCacheResponseProto, error)
	// *
	// Refresh job retention.
	RefreshJobRetentionSettings(ctx context.Context, in *RefreshJobRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshJobRetentionSettingsResponseProto, error)
	// *
	// Refresh log retention
	RefreshLogRetentionSettings(ctx context.Context, in *RefreshLogRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshLogRetentionSettingsResponseProto, error)
}

type hSAdminRefreshProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewHSAdminRefreshProtocolServiceClient(cc *grpc.ClientConn) HSAdminRefreshProtocolServiceClient {
	return &hSAdminRefreshProtocolServiceClient{cc}
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshAdminAcls(ctx context.Context, in *RefreshAdminAclsRequestProto, opts ...grpc.CallOption) (*RefreshAdminAclsResponseProto, error) {
	out := new(RefreshAdminAclsResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.mapreduce.HSAdminRefreshProtocolService/refreshAdminAcls", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshLoadedJobCache(ctx context.Context, in *RefreshLoadedJobCacheRequestProto, opts ...grpc.CallOption) (*RefreshLoadedJobCacheResponseProto, error) {
	out := new(RefreshLoadedJobCacheResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.mapreduce.HSAdminRefreshProtocolService/refreshLoadedJobCache", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshJobRetentionSettings(ctx context.Context, in *RefreshJobRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshJobRetentionSettingsResponseProto, error) {
	out := new(RefreshJobRetentionSettingsResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.mapreduce.HSAdminRefreshProtocolService/refreshJobRetentionSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hSAdminRefreshProtocolServiceClient) RefreshLogRetentionSettings(ctx context.Context, in *RefreshLogRetentionSettingsRequestProto, opts ...grpc.CallOption) (*RefreshLogRetentionSettingsResponseProto, error) {
	out := new(RefreshLogRetentionSettingsResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.mapreduce.HSAdminRefreshProtocolService/refreshLogRetentionSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HSAdminRefreshProtocolService service

type HSAdminRefreshProtocolServiceServer interface {
	// *
	// Refresh admin acls
	RefreshAdminAcls(context.Context, *RefreshAdminAclsRequestProto) (*RefreshAdminAclsResponseProto, error)
	// *
	// Refresh loaded job cache
	RefreshLoadedJobCache(context.Context, *RefreshLoadedJobCacheRequestProto) (*RefreshLoadedJobCacheResponseProto, error)
	// *
	// Refresh job retention.
	RefreshJobRetentionSettings(context.Context, *RefreshJobRetentionSettingsRequestProto) (*RefreshJobRetentionSettingsResponseProto, error)
	// *
	// Refresh log retention
	RefreshLogRetentionSettings(context.Context, *RefreshLogRetentionSettingsRequestProto) (*RefreshLogRetentionSettingsResponseProto, error)
}

func RegisterHSAdminRefreshProtocolServiceServer(s *grpc.Server, srv HSAdminRefreshProtocolServiceServer) {
	s.RegisterService(&_HSAdminRefreshProtocolService_serviceDesc, srv)
}

func _HSAdminRefreshProtocolService_RefreshAdminAcls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAdminAclsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshAdminAcls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.mapreduce.HSAdminRefreshProtocolService/RefreshAdminAcls",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshAdminAcls(ctx, req.(*RefreshAdminAclsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshLoadedJobCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLoadedJobCacheRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLoadedJobCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.mapreduce.HSAdminRefreshProtocolService/RefreshLoadedJobCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLoadedJobCache(ctx, req.(*RefreshLoadedJobCacheRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshJobRetentionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshJobRetentionSettingsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshJobRetentionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.mapreduce.HSAdminRefreshProtocolService/RefreshJobRetentionSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshJobRetentionSettings(ctx, req.(*RefreshJobRetentionSettingsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _HSAdminRefreshProtocolService_RefreshLogRetentionSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshLogRetentionSettingsRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLogRetentionSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.mapreduce.HSAdminRefreshProtocolService/RefreshLogRetentionSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HSAdminRefreshProtocolServiceServer).RefreshLogRetentionSettings(ctx, req.(*RefreshLogRetentionSettingsRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _HSAdminRefreshProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hadoop.mapreduce.HSAdminRefreshProtocolService",
	HandlerType: (*HSAdminRefreshProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "refreshAdminAcls",
			Handler:    _HSAdminRefreshProtocolService_RefreshAdminAcls_Handler,
		},
		{
			MethodName: "refreshLoadedJobCache",
			Handler:    _HSAdminRefreshProtocolService_RefreshLoadedJobCache_Handler,
		},
		{
			MethodName: "refreshJobRetentionSettings",
			Handler:    _HSAdminRefreshProtocolService_RefreshJobRetentionSettings_Handler,
		},
		{
			MethodName: "refreshLogRetentionSettings",
			Handler:    _HSAdminRefreshProtocolService_RefreshLogRetentionSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor3,
}

func init() { proto.RegisterFile("HSAdminRefreshProtocol.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0x31, 0x4e, 0xc3, 0x30,
	0x18, 0x85, 0x65, 0x89, 0xe9, 0x9f, 0x2a, 0x4b, 0x2c, 0xa5, 0x05, 0x11, 0x90, 0x0a, 0x0c, 0x46,
	0x2a, 0x2c, 0xb0, 0xb5, 0x2c, 0x08, 0x15, 0x09, 0x25, 0x27, 0x08, 0xc9, 0x4f, 0x12, 0xa9, 0xf5,
	0x6f, 0x6c, 0xb7, 0x07, 0x60, 0xe2, 0x00, 0x1c, 0x80, 0xdb, 0x70, 0x2d, 0x68, 0x9a, 0x21, 0x6d,
	0xed, 0x24, 0x4c, 0x89, 0xe4, 0xf7, 0x3e, 0x3d, 0xbd, 0x67, 0xc3, 0xe0, 0x31, 0x9a, 0xa4, 0x8b,
	0x42, 0x86, 0xf8, 0xa6, 0xd1, 0xe4, 0x2f, 0x9a, 0x2c, 0x25, 0x34, 0x17, 0x6a, 0xfd, 0xc3, 0x7b,
	0x79, 0x9c, 0x12, 0x29, 0xb1, 0x88, 0x95, 0xc6, 0x74, 0x99, 0x60, 0x70, 0x0c, 0x83, 0x4a, 0x5a,
	0xda, 0x26, 0xc9, 0xdc, 0x84, 0xf8, 0xbe, 0x44, 0x63, 0x4b, 0x6b, 0x70, 0x02, 0xc3, 0xfd, 0x73,
	0xa3, 0x48, 0x1a, 0xdc, 0x08, 0xce, 0xe0, 0xb4, 0x12, 0xcc, 0x28, 0x4e, 0x31, 0x7d, 0xa2, 0xd7,
	0x87, 0x38, 0xc9, 0x71, 0x8b, 0x72, 0x0e, 0x81, 0x47, 0x54, 0x47, 0x5d, 0xc2, 0xa8, 0x52, 0xfd,
	0x9d, 0x87, 0x68, 0x51, 0xda, 0x82, 0x64, 0x84, 0xd6, 0x16, 0x32, 0xdb, 0x8e, 0x75, 0x05, 0x17,
	0x8d, 0x52, 0x37, 0x76, 0x46, 0x59, 0x57, 0xac, 0x5b, 0x5a, 0xc3, 0x8e, 0x7f, 0x0e, 0x60, 0xe8,
	0x2e, 0x3b, 0x42, 0xbd, 0x2a, 0x12, 0xe4, 0x06, 0x7a, 0x7a, 0xa7, 0x3b, 0x2e, 0xc4, 0xee, 0x04,
	0xa2, 0xa9, 0xff, 0xfe, 0x75, 0x17, 0x7d, 0x2d, 0x16, 0xff, 0x60, 0x70, 0xa8, 0x5d, 0x5d, 0xf3,
	0x1b, 0x2f, 0xca, 0xbf, 0x5c, 0xff, 0xb6, 0xb3, 0xa9, 0x1e, 0xe2, 0x8b, 0xc1, 0x91, 0xf6, 0xef,
	0xc3, 0xef, 0xbc, 0xd4, 0xb6, 0xe5, 0xfb, 0xf7, 0xff, 0xb4, 0x7a, 0x62, 0xb9, 0xf6, 0x6d, 0x88,
	0xd5, 0x76, 0x73, 0x1a, 0x62, 0xb5, 0xde, 0xa4, 0xe9, 0x33, 0x8c, 0x48, 0x67, 0x22, 0x56, 0xeb,
	0x22, 0xf7, 0x39, 0xab, 0xb1, 0xc8, 0xcd, 0xe6, 0x01, 0x4f, 0x3d, 0xcf, 0xbb, 0xfc, 0x9a, 0x4f,
	0xc6, 0xbe, 0x19, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xd5, 0xd7, 0x99, 0x03, 0x04, 0x00,
	0x00,
}
