// Code generated by protoc-gen-go.
// source: erasurecoding.proto
// DO NOT EDIT!

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	erasurecoding.proto

It has these top-level messages:
	SetErasureCodingPolicyRequestProto
	SetErasureCodingPolicyResponseProto
	GetErasureCodingPoliciesRequestProto
	GetErasureCodingPoliciesResponseProto
	GetErasureCodingPolicyRequestProto
	GetErasureCodingPolicyResponseProto
	BlockECReconstructionInfoProto
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hadoop_hdfs "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetErasureCodingPolicyRequestProto struct {
	Src              *string                               `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	EcPolicy         *hadoop_hdfs.ErasureCodingPolicyProto `protobuf:"bytes,2,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *SetErasureCodingPolicyRequestProto) Reset()         { *m = SetErasureCodingPolicyRequestProto{} }
func (m *SetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *SetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

func (m *SetErasureCodingPolicyRequestProto) GetEcPolicy() *hadoop_hdfs.ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

type SetErasureCodingPolicyResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SetErasureCodingPolicyResponseProto) Reset()         { *m = SetErasureCodingPolicyResponseProto{} }
func (m *SetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*SetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*SetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

type GetErasureCodingPoliciesRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetErasureCodingPoliciesRequestProto) Reset()         { *m = GetErasureCodingPoliciesRequestProto{} }
func (m *GetErasureCodingPoliciesRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

type GetErasureCodingPoliciesResponseProto struct {
	EcPolicies       []*hadoop_hdfs.ErasureCodingPolicyProto `protobuf:"bytes,1,rep,name=ecPolicies" json:"ecPolicies,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *GetErasureCodingPoliciesResponseProto) Reset()         { *m = GetErasureCodingPoliciesResponseProto{} }
func (m *GetErasureCodingPoliciesResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPoliciesResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPoliciesResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

func (m *GetErasureCodingPoliciesResponseProto) GetEcPolicies() []*hadoop_hdfs.ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicies
	}
	return nil
}

type GetErasureCodingPolicyRequestProto struct {
	Src              *string `protobuf:"bytes,1,req,name=src" json:"src,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetErasureCodingPolicyRequestProto) Reset()         { *m = GetErasureCodingPolicyRequestProto{} }
func (m *GetErasureCodingPolicyRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyRequestProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *GetErasureCodingPolicyRequestProto) GetSrc() string {
	if m != nil && m.Src != nil {
		return *m.Src
	}
	return ""
}

type GetErasureCodingPolicyResponseProto struct {
	EcPolicy         *hadoop_hdfs.ErasureCodingPolicyProto `protobuf:"bytes,1,opt,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *GetErasureCodingPolicyResponseProto) Reset()         { *m = GetErasureCodingPolicyResponseProto{} }
func (m *GetErasureCodingPolicyResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetErasureCodingPolicyResponseProto) ProtoMessage()    {}
func (*GetErasureCodingPolicyResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *GetErasureCodingPolicyResponseProto) GetEcPolicy() *hadoop_hdfs.ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

// *
// Block erasure coding reconstruction info
type BlockECReconstructionInfoProto struct {
	Block              *hadoop_hdfs.ExtendedBlockProto       `protobuf:"bytes,1,req,name=block" json:"block,omitempty"`
	SourceDnInfos      *hadoop_hdfs.DatanodeInfosProto       `protobuf:"bytes,2,req,name=sourceDnInfos" json:"sourceDnInfos,omitempty"`
	TargetDnInfos      *hadoop_hdfs.DatanodeInfosProto       `protobuf:"bytes,3,req,name=targetDnInfos" json:"targetDnInfos,omitempty"`
	TargetStorageUuids *hadoop_hdfs.StorageUuidsProto        `protobuf:"bytes,4,req,name=targetStorageUuids" json:"targetStorageUuids,omitempty"`
	TargetStorageTypes *hadoop_hdfs.StorageTypesProto        `protobuf:"bytes,5,req,name=targetStorageTypes" json:"targetStorageTypes,omitempty"`
	LiveBlockIndices   []byte                                `protobuf:"bytes,6,req,name=liveBlockIndices" json:"liveBlockIndices,omitempty"`
	EcPolicy           *hadoop_hdfs.ErasureCodingPolicyProto `protobuf:"bytes,7,req,name=ecPolicy" json:"ecPolicy,omitempty"`
	XXX_unrecognized   []byte                                `json:"-"`
}

func (m *BlockECReconstructionInfoProto) Reset()                    { *m = BlockECReconstructionInfoProto{} }
func (m *BlockECReconstructionInfoProto) String() string            { return proto.CompactTextString(m) }
func (*BlockECReconstructionInfoProto) ProtoMessage()               {}
func (*BlockECReconstructionInfoProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlockECReconstructionInfoProto) GetBlock() *hadoop_hdfs.ExtendedBlockProto {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetSourceDnInfos() *hadoop_hdfs.DatanodeInfosProto {
	if m != nil {
		return m.SourceDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetDnInfos() *hadoop_hdfs.DatanodeInfosProto {
	if m != nil {
		return m.TargetDnInfos
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageUuids() *hadoop_hdfs.StorageUuidsProto {
	if m != nil {
		return m.TargetStorageUuids
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetTargetStorageTypes() *hadoop_hdfs.StorageTypesProto {
	if m != nil {
		return m.TargetStorageTypes
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetLiveBlockIndices() []byte {
	if m != nil {
		return m.LiveBlockIndices
	}
	return nil
}

func (m *BlockECReconstructionInfoProto) GetEcPolicy() *hadoop_hdfs.ErasureCodingPolicyProto {
	if m != nil {
		return m.EcPolicy
	}
	return nil
}

func init() {
	proto.RegisterType((*SetErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.SetErasureCodingPolicyRequestProto")
	proto.RegisterType((*SetErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.SetErasureCodingPolicyResponseProto")
	proto.RegisterType((*GetErasureCodingPoliciesRequestProto)(nil), "hadoop.hdfs.GetErasureCodingPoliciesRequestProto")
	proto.RegisterType((*GetErasureCodingPoliciesResponseProto)(nil), "hadoop.hdfs.GetErasureCodingPoliciesResponseProto")
	proto.RegisterType((*GetErasureCodingPolicyRequestProto)(nil), "hadoop.hdfs.GetErasureCodingPolicyRequestProto")
	proto.RegisterType((*GetErasureCodingPolicyResponseProto)(nil), "hadoop.hdfs.GetErasureCodingPolicyResponseProto")
	proto.RegisterType((*BlockECReconstructionInfoProto)(nil), "hadoop.hdfs.BlockECReconstructionInfoProto")
}

func init() { proto.RegisterFile("erasurecoding.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 405 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x95, 0x0d, 0xcb, 0xc7, 0x14, 0xa4, 0x55, 0xf6, 0x52, 0x71, 0x58, 0x56, 0x2e, 0x41,
	0x15, 0x87, 0x1c, 0x2a, 0xc1, 0x15, 0xd1, 0x0f, 0x55, 0xbd, 0xa0, 0x2a, 0x85, 0x07, 0x30, 0xf6,
	0x34, 0x89, 0x88, 0xec, 0x60, 0x3b, 0x88, 0xbe, 0x0d, 0x0f, 0xc9, 0x03, 0xe0, 0xd8, 0x80, 0x62,
	0x35, 0x15, 0xa5, 0x97, 0xc8, 0x9a, 0xf9, 0xff, 0x7f, 0x33, 0x1e, 0x4f, 0xe0, 0x16, 0x15, 0xd5,
	0xad, 0x42, 0x26, 0x79, 0x25, 0x8a, 0xac, 0x51, 0xd2, 0xc8, 0x64, 0x54, 0x52, 0x2e, 0x65, 0x93,
	0x95, 0x7c, 0xaf, 0x9f, 0x43, 0xf7, 0xf5, 0x09, 0x72, 0x00, 0xb2, 0x43, 0xb3, 0xf2, 0x96, 0x85,
	0xb3, 0x6c, 0x65, 0x5d, 0xb1, 0x43, 0x8e, 0x5f, 0x5b, 0xd4, 0x66, 0xeb, 0xec, 0x37, 0x10, 0x6b,
	0xc5, 0xc6, 0xd1, 0xfd, 0xd5, 0xf4, 0x49, 0xde, 0x1d, 0x93, 0xf7, 0xf0, 0x18, 0x99, 0x57, 0x8e,
	0xaf, 0xee, 0xa3, 0xe9, 0x68, 0x96, 0x66, 0xbd, 0x1a, 0xd9, 0x00, 0xd1, 0xa1, 0xf2, 0xbf, 0x36,
	0x92, 0xc2, 0xe4, 0x54, 0x69, 0xdd, 0x48, 0xa1, 0xd1, 0x19, 0xc8, 0x2b, 0x78, 0xb9, 0x1e, 0x92,
	0x55, 0xa8, 0xfb, 0x3d, 0x12, 0x01, 0xe9, 0x69, 0x5d, 0x0f, 0x98, 0xac, 0x00, 0x7e, 0xf7, 0x60,
	0x53, 0xf6, 0x4e, 0xf1, 0xf9, 0xcd, 0xf7, 0x8c, 0xe4, 0x2d, 0x90, 0xf5, 0x05, 0x93, 0x23, 0x25,
	0x4c, 0xd6, 0xff, 0xbe, 0x76, 0x30, 0xe0, 0xe8, 0xb2, 0x01, 0xff, 0x8c, 0xe1, 0x6e, 0x5e, 0x4b,
	0xf6, 0x65, 0xb5, 0xc8, 0xed, 0x3a, 0x08, 0x6d, 0x54, 0xcb, 0x4c, 0x25, 0xc5, 0x46, 0xec, 0xa5,
	0xaf, 0xf2, 0x06, 0xae, 0x3f, 0x77, 0x0a, 0xd7, 0xe0, 0x68, 0xf6, 0x22, 0x2c, 0xf1, 0xdd, 0xa0,
	0xe0, 0xc8, 0x1d, 0xc3, 0xc3, 0xbd, 0xda, 0x8e, 0xf0, 0x99, 0x96, 0xad, 0x62, 0xb8, 0x74, 0x2c,
	0x6d, 0x57, 0xe0, 0xd8, 0xbe, 0xa4, 0x86, 0x0a, 0xc9, 0xd1, 0x29, 0xbc, 0x3d, 0x74, 0x75, 0x18,
	0x43, 0x55, 0x81, 0xe6, 0x0f, 0x26, 0x3e, 0x13, 0x13, 0xb8, 0x92, 0x0f, 0x90, 0xf8, 0xc0, 0xce,
	0x48, 0x45, 0x0b, 0xfc, 0xd4, 0x56, 0x5c, 0x8f, 0x1f, 0x38, 0xd6, 0x5d, 0xc0, 0xea, 0x0b, 0x3c,
	0x6a, 0xc0, 0x79, 0xc4, 0xfb, 0x78, 0x68, 0xec, 0xa2, 0x5c, 0x9f, 0xe6, 0x39, 0xc1, 0x10, 0xcf,
	0x25, 0x92, 0xd7, 0x70, 0x53, 0x57, 0xdf, 0xd0, 0x8d, 0x71, 0x23, 0x78, 0xc5, 0x2c, 0xed, 0xa1,
	0xa5, 0x3d, 0xcd, 0x8f, 0xe2, 0xc1, 0xb3, 0x3f, 0x72, 0x15, 0xff, 0xf7, 0xd9, 0xe7, 0xef, 0x20,
	0x95, 0xaa, 0xc8, 0x68, 0x43, 0x59, 0x89, 0x81, 0xd9, 0xfd, 0xf2, 0x4c, 0xd6, 0xfe, 0x30, 0xbf,
	0x0d, 0x61, 0x5d, 0x4c, 0xff, 0x88, 0xa2, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x01, 0xdd, 0x67,
	0x30, 0x42, 0x04, 0x00, 0x00,
}
