// Code generated by protoc-gen-go.
// source: inotify.proto
// DO NOT EDIT!

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	inotify.proto

It has these top-level messages:
	EventProto
	EventBatchProto
	CreateEventProto
	CloseEventProto
	TruncateEventProto
	AppendEventProto
	RenameEventProto
	MetadataUpdateEventProto
	UnlinkEventProto
	EventsListProto
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hadoop_hdfs1 "."
import hadoop_hdfs2 "."
import hadoop_hdfs "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_EVENT_CREATE   EventType = 0
	EventType_EVENT_CLOSE    EventType = 1
	EventType_EVENT_APPEND   EventType = 2
	EventType_EVENT_RENAME   EventType = 3
	EventType_EVENT_METADATA EventType = 4
	EventType_EVENT_UNLINK   EventType = 5
	EventType_EVENT_TRUNCATE EventType = 6
)

var EventType_name = map[int32]string{
	0: "EVENT_CREATE",
	1: "EVENT_CLOSE",
	2: "EVENT_APPEND",
	3: "EVENT_RENAME",
	4: "EVENT_METADATA",
	5: "EVENT_UNLINK",
	6: "EVENT_TRUNCATE",
}
var EventType_value = map[string]int32{
	"EVENT_CREATE":   0,
	"EVENT_CLOSE":    1,
	"EVENT_APPEND":   2,
	"EVENT_RENAME":   3,
	"EVENT_METADATA": 4,
	"EVENT_UNLINK":   5,
	"EVENT_TRUNCATE": 6,
}

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}
func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (x *EventType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EventType_value, data, "EventType")
	if err != nil {
		return err
	}
	*x = EventType(value)
	return nil
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type INodeType int32

const (
	INodeType_I_TYPE_FILE      INodeType = 0
	INodeType_I_TYPE_DIRECTORY INodeType = 1
	INodeType_I_TYPE_SYMLINK   INodeType = 2
)

var INodeType_name = map[int32]string{
	0: "I_TYPE_FILE",
	1: "I_TYPE_DIRECTORY",
	2: "I_TYPE_SYMLINK",
}
var INodeType_value = map[string]int32{
	"I_TYPE_FILE":      0,
	"I_TYPE_DIRECTORY": 1,
	"I_TYPE_SYMLINK":   2,
}

func (x INodeType) Enum() *INodeType {
	p := new(INodeType)
	*p = x
	return p
}
func (x INodeType) String() string {
	return proto.EnumName(INodeType_name, int32(x))
}
func (x *INodeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(INodeType_value, data, "INodeType")
	if err != nil {
		return err
	}
	*x = INodeType(value)
	return nil
}
func (INodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MetadataUpdateType int32

const (
	MetadataUpdateType_META_TYPE_TIMES       MetadataUpdateType = 0
	MetadataUpdateType_META_TYPE_REPLICATION MetadataUpdateType = 1
	MetadataUpdateType_META_TYPE_OWNER       MetadataUpdateType = 2
	MetadataUpdateType_META_TYPE_PERMS       MetadataUpdateType = 3
	MetadataUpdateType_META_TYPE_ACLS        MetadataUpdateType = 4
	MetadataUpdateType_META_TYPE_XATTRS      MetadataUpdateType = 5
)

var MetadataUpdateType_name = map[int32]string{
	0: "META_TYPE_TIMES",
	1: "META_TYPE_REPLICATION",
	2: "META_TYPE_OWNER",
	3: "META_TYPE_PERMS",
	4: "META_TYPE_ACLS",
	5: "META_TYPE_XATTRS",
}
var MetadataUpdateType_value = map[string]int32{
	"META_TYPE_TIMES":       0,
	"META_TYPE_REPLICATION": 1,
	"META_TYPE_OWNER":       2,
	"META_TYPE_PERMS":       3,
	"META_TYPE_ACLS":        4,
	"META_TYPE_XATTRS":      5,
}

func (x MetadataUpdateType) Enum() *MetadataUpdateType {
	p := new(MetadataUpdateType)
	*p = x
	return p
}
func (x MetadataUpdateType) String() string {
	return proto.EnumName(MetadataUpdateType_name, int32(x))
}
func (x *MetadataUpdateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MetadataUpdateType_value, data, "MetadataUpdateType")
	if err != nil {
		return err
	}
	*x = MetadataUpdateType(value)
	return nil
}
func (MetadataUpdateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type EventProto struct {
	Type             *EventType `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.EventType" json:"type,omitempty"`
	Contents         []byte     `protobuf:"bytes,2,req,name=contents" json:"contents,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *EventProto) Reset()                    { *m = EventProto{} }
func (m *EventProto) String() string            { return proto.CompactTextString(m) }
func (*EventProto) ProtoMessage()               {}
func (*EventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *EventProto) GetType() EventType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return EventType_EVENT_CREATE
}

func (m *EventProto) GetContents() []byte {
	if m != nil {
		return m.Contents
	}
	return nil
}

type EventBatchProto struct {
	Txid             *int64        `protobuf:"varint,1,req,name=txid" json:"txid,omitempty"`
	Events           []*EventProto `protobuf:"bytes,2,rep,name=events" json:"events,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *EventBatchProto) Reset()                    { *m = EventBatchProto{} }
func (m *EventBatchProto) String() string            { return proto.CompactTextString(m) }
func (*EventBatchProto) ProtoMessage()               {}
func (*EventBatchProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EventBatchProto) GetTxid() int64 {
	if m != nil && m.Txid != nil {
		return *m.Txid
	}
	return 0
}

func (m *EventBatchProto) GetEvents() []*EventProto {
	if m != nil {
		return m.Events
	}
	return nil
}

type CreateEventProto struct {
	Type             *INodeType                     `protobuf:"varint,1,req,name=type,enum=hadoop.hdfs.INodeType" json:"type,omitempty"`
	Path             *string                        `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	Ctime            *int64                         `protobuf:"varint,3,req,name=ctime" json:"ctime,omitempty"`
	OwnerName        *string                        `protobuf:"bytes,4,req,name=ownerName" json:"ownerName,omitempty"`
	GroupName        *string                        `protobuf:"bytes,5,req,name=groupName" json:"groupName,omitempty"`
	Perms            *hadoop_hdfs.FsPermissionProto `protobuf:"bytes,6,req,name=perms" json:"perms,omitempty"`
	Replication      *int32                         `protobuf:"varint,7,opt,name=replication" json:"replication,omitempty"`
	SymlinkTarget    *string                        `protobuf:"bytes,8,opt,name=symlinkTarget" json:"symlinkTarget,omitempty"`
	Overwrite        *bool                          `protobuf:"varint,9,opt,name=overwrite" json:"overwrite,omitempty"`
	DefaultBlockSize *int64                         `protobuf:"varint,10,opt,name=defaultBlockSize,def=0" json:"defaultBlockSize,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *CreateEventProto) Reset()                    { *m = CreateEventProto{} }
func (m *CreateEventProto) String() string            { return proto.CompactTextString(m) }
func (*CreateEventProto) ProtoMessage()               {}
func (*CreateEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_CreateEventProto_DefaultBlockSize int64 = 0

func (m *CreateEventProto) GetType() INodeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return INodeType_I_TYPE_FILE
}

func (m *CreateEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CreateEventProto) GetCtime() int64 {
	if m != nil && m.Ctime != nil {
		return *m.Ctime
	}
	return 0
}

func (m *CreateEventProto) GetOwnerName() string {
	if m != nil && m.OwnerName != nil {
		return *m.OwnerName
	}
	return ""
}

func (m *CreateEventProto) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *CreateEventProto) GetPerms() *hadoop_hdfs.FsPermissionProto {
	if m != nil {
		return m.Perms
	}
	return nil
}

func (m *CreateEventProto) GetReplication() int32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *CreateEventProto) GetSymlinkTarget() string {
	if m != nil && m.SymlinkTarget != nil {
		return *m.SymlinkTarget
	}
	return ""
}

func (m *CreateEventProto) GetOverwrite() bool {
	if m != nil && m.Overwrite != nil {
		return *m.Overwrite
	}
	return false
}

func (m *CreateEventProto) GetDefaultBlockSize() int64 {
	if m != nil && m.DefaultBlockSize != nil {
		return *m.DefaultBlockSize
	}
	return Default_CreateEventProto_DefaultBlockSize
}

type CloseEventProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	FileSize         *int64  `protobuf:"varint,2,req,name=fileSize" json:"fileSize,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CloseEventProto) Reset()                    { *m = CloseEventProto{} }
func (m *CloseEventProto) String() string            { return proto.CompactTextString(m) }
func (*CloseEventProto) ProtoMessage()               {}
func (*CloseEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CloseEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *CloseEventProto) GetFileSize() int64 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *CloseEventProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type TruncateEventProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	FileSize         *int64  `protobuf:"varint,2,req,name=fileSize" json:"fileSize,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TruncateEventProto) Reset()                    { *m = TruncateEventProto{} }
func (m *TruncateEventProto) String() string            { return proto.CompactTextString(m) }
func (*TruncateEventProto) ProtoMessage()               {}
func (*TruncateEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TruncateEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *TruncateEventProto) GetFileSize() int64 {
	if m != nil && m.FileSize != nil {
		return *m.FileSize
	}
	return 0
}

func (m *TruncateEventProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type AppendEventProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	NewBlock         *bool   `protobuf:"varint,2,opt,name=newBlock,def=0" json:"newBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AppendEventProto) Reset()                    { *m = AppendEventProto{} }
func (m *AppendEventProto) String() string            { return proto.CompactTextString(m) }
func (*AppendEventProto) ProtoMessage()               {}
func (*AppendEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

const Default_AppendEventProto_NewBlock bool = false

func (m *AppendEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *AppendEventProto) GetNewBlock() bool {
	if m != nil && m.NewBlock != nil {
		return *m.NewBlock
	}
	return Default_AppendEventProto_NewBlock
}

type RenameEventProto struct {
	SrcPath          *string `protobuf:"bytes,1,req,name=srcPath" json:"srcPath,omitempty"`
	DestPath         *string `protobuf:"bytes,2,req,name=destPath" json:"destPath,omitempty"`
	Timestamp        *int64  `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RenameEventProto) Reset()                    { *m = RenameEventProto{} }
func (m *RenameEventProto) String() string            { return proto.CompactTextString(m) }
func (*RenameEventProto) ProtoMessage()               {}
func (*RenameEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RenameEventProto) GetSrcPath() string {
	if m != nil && m.SrcPath != nil {
		return *m.SrcPath
	}
	return ""
}

func (m *RenameEventProto) GetDestPath() string {
	if m != nil && m.DestPath != nil {
		return *m.DestPath
	}
	return ""
}

func (m *RenameEventProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type MetadataUpdateEventProto struct {
	Path             *string                        `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Type             *MetadataUpdateType            `protobuf:"varint,2,req,name=type,enum=hadoop.hdfs.MetadataUpdateType" json:"type,omitempty"`
	Mtime            *int64                         `protobuf:"varint,3,opt,name=mtime" json:"mtime,omitempty"`
	Atime            *int64                         `protobuf:"varint,4,opt,name=atime" json:"atime,omitempty"`
	Replication      *int32                         `protobuf:"varint,5,opt,name=replication" json:"replication,omitempty"`
	OwnerName        *string                        `protobuf:"bytes,6,opt,name=ownerName" json:"ownerName,omitempty"`
	GroupName        *string                        `protobuf:"bytes,7,opt,name=groupName" json:"groupName,omitempty"`
	Perms            *hadoop_hdfs.FsPermissionProto `protobuf:"bytes,8,opt,name=perms" json:"perms,omitempty"`
	Acls             []*hadoop_hdfs1.AclEntryProto  `protobuf:"bytes,9,rep,name=acls" json:"acls,omitempty"`
	XAttrs           []*hadoop_hdfs2.XAttrProto     `protobuf:"bytes,10,rep,name=xAttrs" json:"xAttrs,omitempty"`
	XAttrsRemoved    *bool                          `protobuf:"varint,11,opt,name=xAttrsRemoved" json:"xAttrsRemoved,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *MetadataUpdateEventProto) Reset()                    { *m = MetadataUpdateEventProto{} }
func (m *MetadataUpdateEventProto) String() string            { return proto.CompactTextString(m) }
func (*MetadataUpdateEventProto) ProtoMessage()               {}
func (*MetadataUpdateEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MetadataUpdateEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *MetadataUpdateEventProto) GetType() MetadataUpdateType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MetadataUpdateType_META_TYPE_TIMES
}

func (m *MetadataUpdateEventProto) GetMtime() int64 {
	if m != nil && m.Mtime != nil {
		return *m.Mtime
	}
	return 0
}

func (m *MetadataUpdateEventProto) GetAtime() int64 {
	if m != nil && m.Atime != nil {
		return *m.Atime
	}
	return 0
}

func (m *MetadataUpdateEventProto) GetReplication() int32 {
	if m != nil && m.Replication != nil {
		return *m.Replication
	}
	return 0
}

func (m *MetadataUpdateEventProto) GetOwnerName() string {
	if m != nil && m.OwnerName != nil {
		return *m.OwnerName
	}
	return ""
}

func (m *MetadataUpdateEventProto) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *MetadataUpdateEventProto) GetPerms() *hadoop_hdfs.FsPermissionProto {
	if m != nil {
		return m.Perms
	}
	return nil
}

func (m *MetadataUpdateEventProto) GetAcls() []*hadoop_hdfs1.AclEntryProto {
	if m != nil {
		return m.Acls
	}
	return nil
}

func (m *MetadataUpdateEventProto) GetXAttrs() []*hadoop_hdfs2.XAttrProto {
	if m != nil {
		return m.XAttrs
	}
	return nil
}

func (m *MetadataUpdateEventProto) GetXAttrsRemoved() bool {
	if m != nil && m.XAttrsRemoved != nil {
		return *m.XAttrsRemoved
	}
	return false
}

type UnlinkEventProto struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Timestamp        *int64  `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UnlinkEventProto) Reset()                    { *m = UnlinkEventProto{} }
func (m *UnlinkEventProto) String() string            { return proto.CompactTextString(m) }
func (*UnlinkEventProto) ProtoMessage()               {}
func (*UnlinkEventProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UnlinkEventProto) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *UnlinkEventProto) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type EventsListProto struct {
	Events           []*EventProto      `protobuf:"bytes,1,rep,name=events" json:"events,omitempty"`
	FirstTxid        *int64             `protobuf:"varint,2,req,name=firstTxid" json:"firstTxid,omitempty"`
	LastTxid         *int64             `protobuf:"varint,3,req,name=lastTxid" json:"lastTxid,omitempty"`
	SyncTxid         *int64             `protobuf:"varint,4,req,name=syncTxid" json:"syncTxid,omitempty"`
	Batch            []*EventBatchProto `protobuf:"bytes,5,rep,name=batch" json:"batch,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *EventsListProto) Reset()                    { *m = EventsListProto{} }
func (m *EventsListProto) String() string            { return proto.CompactTextString(m) }
func (*EventsListProto) ProtoMessage()               {}
func (*EventsListProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EventsListProto) GetEvents() []*EventProto {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *EventsListProto) GetFirstTxid() int64 {
	if m != nil && m.FirstTxid != nil {
		return *m.FirstTxid
	}
	return 0
}

func (m *EventsListProto) GetLastTxid() int64 {
	if m != nil && m.LastTxid != nil {
		return *m.LastTxid
	}
	return 0
}

func (m *EventsListProto) GetSyncTxid() int64 {
	if m != nil && m.SyncTxid != nil {
		return *m.SyncTxid
	}
	return 0
}

func (m *EventsListProto) GetBatch() []*EventBatchProto {
	if m != nil {
		return m.Batch
	}
	return nil
}

func init() {
	proto.RegisterType((*EventProto)(nil), "hadoop.hdfs.EventProto")
	proto.RegisterType((*EventBatchProto)(nil), "hadoop.hdfs.EventBatchProto")
	proto.RegisterType((*CreateEventProto)(nil), "hadoop.hdfs.CreateEventProto")
	proto.RegisterType((*CloseEventProto)(nil), "hadoop.hdfs.CloseEventProto")
	proto.RegisterType((*TruncateEventProto)(nil), "hadoop.hdfs.TruncateEventProto")
	proto.RegisterType((*AppendEventProto)(nil), "hadoop.hdfs.AppendEventProto")
	proto.RegisterType((*RenameEventProto)(nil), "hadoop.hdfs.RenameEventProto")
	proto.RegisterType((*MetadataUpdateEventProto)(nil), "hadoop.hdfs.MetadataUpdateEventProto")
	proto.RegisterType((*UnlinkEventProto)(nil), "hadoop.hdfs.UnlinkEventProto")
	proto.RegisterType((*EventsListProto)(nil), "hadoop.hdfs.EventsListProto")
	proto.RegisterEnum("hadoop.hdfs.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("hadoop.hdfs.INodeType", INodeType_name, INodeType_value)
	proto.RegisterEnum("hadoop.hdfs.MetadataUpdateType", MetadataUpdateType_name, MetadataUpdateType_value)
}

func init() { proto.RegisterFile("inotify.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 912 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x49, 0xdc, 0x36, 0x27, 0xdb, 0xad, 0x65, 0x16, 0x30, 0xd5, 0x0a, 0x4a, 0x04, 0x52,
	0x55, 0x89, 0x80, 0x0a, 0x37, 0xec, 0x9d, 0x9b, 0x4e, 0x25, 0x8b, 0xc4, 0xb5, 0x26, 0xee, 0xb2,
	0xbd, 0xaa, 0x66, 0xed, 0x49, 0x63, 0xad, 0x63, 0x5b, 0x9e, 0xe9, 0x4f, 0x78, 0x06, 0x1e, 0x80,
	0x4b, 0xae, 0x79, 0x16, 0xde, 0x85, 0x57, 0x60, 0x7e, 0x5c, 0x3b, 0x6e, 0x40, 0xed, 0x05, 0x77,
	0x3e, 0xdf, 0xf9, 0x7c, 0xe6, 0x9b, 0xf3, 0x67, 0xc3, 0x6e, 0x92, 0xe5, 0x3c, 0x99, 0xaf, 0x46,
	0x45, 0x99, 0xf3, 0xdc, 0x1e, 0x2c, 0x48, 0x9c, 0xe7, 0xc5, 0x68, 0x11, 0xcf, 0xd9, 0x7e, 0x9f,
	0x44, 0xa9, 0xc6, 0xf7, 0x07, 0xf7, 0x84, 0xf3, 0xb2, 0x32, 0x40, 0x7a, 0xf5, 0xf3, 0x30, 0x04,
	0x40, 0xb7, 0x34, 0xe3, 0x81, 0x7a, 0xfd, 0x08, 0x7a, 0x7c, 0x55, 0x50, 0xc7, 0x38, 0xe8, 0x1c,
	0xbe, 0x3c, 0xfe, 0x74, 0xb4, 0x16, 0x6d, 0xa4, 0x68, 0xa1, 0xf0, 0x62, 0xc5, 0xb1, 0xf7, 0x61,
	0x27, 0xca, 0x33, 0x2e, 0x40, 0xe6, 0x74, 0x04, 0xff, 0x05, 0xae, 0xed, 0xe1, 0x5b, 0xd8, 0x53,
	0xf4, 0x13, 0xc2, 0xa3, 0x85, 0x0e, 0x6d, 0x8b, 0xd0, 0xf7, 0x49, 0xac, 0x42, 0x77, 0xb1, 0x7a,
	0xb6, 0xbf, 0x83, 0x2d, 0x7a, 0x5b, 0x05, 0xe8, 0x1e, 0x0e, 0x8e, 0x3f, 0xdb, 0x3c, 0x50, 0xbd,
	0x8c, 0x2b, 0xda, 0xf0, 0xef, 0x0e, 0x58, 0xe3, 0x92, 0x12, 0x4e, 0x9f, 0x29, 0xda, 0xf3, 0xf3,
	0x98, 0xae, 0x89, 0x16, 0x2a, 0x0a, 0xc2, 0x17, 0x4a, 0x70, 0x1f, 0xab, 0x67, 0xfb, 0x15, 0x98,
	0x11, 0x4f, 0x96, 0xd4, 0xe9, 0x2a, 0x69, 0xda, 0xb0, 0x5f, 0x43, 0x3f, 0xbf, 0xcb, 0x68, 0xe9,
	0x13, 0xe1, 0xe9, 0x29, 0x7a, 0x03, 0x48, 0xef, 0x75, 0x99, 0xdf, 0x14, 0xca, 0x6b, 0x6a, 0x6f,
	0x0d, 0xd8, 0x3f, 0x82, 0x59, 0xd0, 0x72, 0xc9, 0x9c, 0x2d, 0xe1, 0x19, 0x1c, 0x7f, 0xd1, 0x92,
	0x74, 0xc6, 0x02, 0xe1, 0x4b, 0x18, 0x4b, 0xf2, 0x4c, 0xdf, 0x4e, 0x93, 0xed, 0x03, 0x18, 0x94,
	0xb4, 0x48, 0x93, 0x88, 0x70, 0xe1, 0x72, 0xb6, 0x0f, 0x8c, 0x43, 0x13, 0xaf, 0x43, 0xf6, 0xd7,
	0xb0, 0xcb, 0x56, 0xcb, 0x34, 0xc9, 0x3e, 0x84, 0xa4, 0xbc, 0xa6, 0xdc, 0xd9, 0x11, 0x9c, 0x3e,
	0x6e, 0x83, 0x4a, 0xf9, 0x2d, 0x2d, 0xef, 0xca, 0x84, 0x53, 0xa7, 0x2f, 0x18, 0x3b, 0xb8, 0x01,
	0xec, 0x6f, 0xc1, 0x8a, 0xe9, 0x9c, 0xdc, 0xa4, 0xfc, 0x24, 0xcd, 0xa3, 0x0f, 0xb3, 0xe4, 0x57,
	0xea, 0x80, 0x20, 0x75, 0xdf, 0x18, 0xdf, 0xe3, 0x0d, 0xd7, 0xf0, 0x0a, 0xf6, 0xc6, 0x69, 0xce,
	0xd6, 0xf3, 0xfd, 0x90, 0x43, 0x63, 0x2d, 0x87, 0xa2, 0x19, 0xe6, 0x49, 0x4a, 0x55, 0xb4, 0x8e,
	0x4a, 0x63, 0x6d, 0x4b, 0x3d, 0x32, 0xa3, 0x8c, 0x93, 0x65, 0x51, 0xe5, 0xb8, 0x01, 0x86, 0xef,
	0xc1, 0x0e, 0xcb, 0x9b, 0x2c, 0x6a, 0xd7, 0xf4, 0xff, 0x3d, 0xc3, 0x03, 0xcb, 0x2d, 0x0a, 0x9a,
	0xc5, 0x4f, 0x9c, 0xf0, 0x15, 0xec, 0x64, 0xf4, 0x4e, 0x5d, 0x5e, 0x9c, 0x20, 0x12, 0xf7, 0xc6,
	0x9c, 0x93, 0x94, 0x51, 0x5c, 0xc3, 0xc3, 0x39, 0x58, 0x98, 0x66, 0xa2, 0xc8, 0x6b, 0xa1, 0x1c,
	0xd8, 0x66, 0x65, 0x14, 0x34, 0xd1, 0x1e, 0x4c, 0x29, 0x39, 0x16, 0x1a, 0x82, 0xa6, 0xe5, 0x6a,
	0xfb, 0x09, 0xc9, 0x7f, 0x76, 0xc1, 0x99, 0x52, 0x4e, 0x62, 0xc2, 0xc9, 0x45, 0x11, 0x3f, 0x9d,
	0x9d, 0x1f, 0xaa, 0x29, 0xe8, 0xa8, 0x29, 0xf8, 0xb2, 0xd5, 0x72, 0xed, 0x40, 0x6b, 0xe3, 0x20,
	0x5a, 0x7f, 0x59, 0xb5, 0xbe, 0x21, 0x5b, 0x5f, 0x19, 0x12, 0x25, 0x0a, 0xed, 0x69, 0x54, 0x19,
	0x8f, 0xdb, 0xd3, 0xdc, 0x6c, 0xcf, 0xd6, 0xc8, 0x6c, 0xa9, 0xd6, 0xfc, 0xaf, 0x91, 0xd9, 0xd6,
	0xde, 0x7f, 0x19, 0x19, 0xd9, 0xd2, 0xcf, 0x1e, 0x99, 0x11, 0xf4, 0xc4, 0x8e, 0x63, 0xa2, 0xcb,
	0xe5, 0xfa, 0xd8, 0x6f, 0xbd, 0xe4, 0x46, 0x29, 0xca, 0x78, 0xb9, 0xd2, 0x2f, 0x28, 0x9e, 0x5c,
	0x38, 0xf7, 0xae, 0x58, 0x84, 0x4c, 0xb4, 0xfc, 0xe6, 0xc2, 0x79, 0x27, 0x5d, 0xd5, 0xc2, 0xd1,
	0x34, 0x39, 0x71, 0xfa, 0x09, 0xd3, 0xa5, 0x98, 0xa1, 0xd8, 0x19, 0xa8, 0x79, 0x6a, 0x83, 0xc3,
	0x53, 0xb0, 0x2e, 0x32, 0x39, 0x81, 0x4f, 0xd4, 0xa8, 0x55, 0xf2, 0xce, 0xe3, 0x92, 0xff, 0x65,
	0x54, 0x5b, 0x93, 0x4d, 0x12, 0x56, 0x45, 0x69, 0x36, 0xa4, 0xf1, 0xac, 0x0d, 0x29, 0x8f, 0x98,
	0x27, 0x25, 0xe3, 0xa1, 0xdc, 0xb5, 0xd5, 0x11, 0x35, 0x20, 0xfb, 0x31, 0x25, 0x95, 0x53, 0xb7,
	0x5c, 0x6d, 0x4b, 0x1f, 0x5b, 0x65, 0x91, 0xf2, 0xf5, 0xb4, 0xef, 0xc1, 0xb6, 0x8f, 0xc1, 0x7c,
	0x2f, 0x57, 0xb9, 0xa8, 0xba, 0x54, 0xf1, 0x7a, 0x53, 0x45, 0xb3, 0xe9, 0xb1, 0xa6, 0x1e, 0xfd,
	0x66, 0x40, 0xbf, 0xfe, 0x66, 0xd8, 0x16, 0xbc, 0x40, 0x6f, 0x91, 0x1f, 0x5e, 0x8d, 0x31, 0x72,
	0x43, 0x64, 0x7d, 0x64, 0xef, 0xc1, 0xa0, 0x42, 0x26, 0xe7, 0x33, 0x64, 0x19, 0x0d, 0xc5, 0x0d,
	0x02, 0xe4, 0x9f, 0x5a, 0x9d, 0x06, 0xc1, 0xc8, 0x77, 0xa7, 0xc8, 0xea, 0x8a, 0xac, 0xbe, 0xd4,
	0xc8, 0x14, 0x85, 0xee, 0xa9, 0x1b, 0xba, 0x56, 0xaf, 0x61, 0x5d, 0xf8, 0x13, 0xcf, 0xff, 0xd9,
	0x32, 0x1b, 0x56, 0x88, 0x2f, 0xfc, 0xb1, 0x3c, 0x6e, 0xeb, 0xe8, 0x0c, 0xfa, 0xf5, 0xc7, 0x40,
	0x9e, 0xed, 0x5d, 0x85, 0x97, 0x01, 0xba, 0x3a, 0xf3, 0x26, 0x52, 0xcc, 0x2b, 0xb0, 0x2a, 0xe0,
	0xd4, 0xc3, 0x68, 0x1c, 0x9e, 0xe3, 0x4b, 0xa1, 0x48, 0xc4, 0xa9, 0xd0, 0xd9, 0xe5, 0x54, 0xc5,
	0xee, 0x1c, 0xfd, 0x6e, 0x80, 0xbd, 0x39, 0x4f, 0xf6, 0xc7, 0xb0, 0x27, 0x25, 0x69, 0x76, 0xe8,
	0x4d, 0xd1, 0x4c, 0x44, 0xfd, 0x1c, 0x3e, 0x69, 0x40, 0x8c, 0x82, 0x89, 0x27, 0xc4, 0x78, 0xe7,
	0xbe, 0x08, 0xdd, 0xe2, 0x9f, 0xff, 0xe2, 0x23, 0x2c, 0xee, 0xdb, 0x02, 0x03, 0x84, 0xa7, 0x33,
	0x7d, 0xe5, 0x06, 0x74, 0xc7, 0x93, 0x99, 0xb8, 0xb2, 0x90, 0xdb, 0x60, 0xef, 0xdc, 0x30, 0xc4,
	0x33, 0xcb, 0x3c, 0xf9, 0x09, 0xbe, 0xc9, 0xcb, 0xeb, 0x11, 0x29, 0x48, 0xb4, 0xa0, 0xad, 0x12,
	0xa9, 0x6f, 0x7d, 0x94, 0x57, 0x7f, 0x03, 0x27, 0xbb, 0x9e, 0xfe, 0x69, 0x50, 0xf5, 0x62, 0x7f,
	0x18, 0xc6, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0xd0, 0x57, 0x29, 0x47, 0x08, 0x00, 0x00,
}
