// Code generated by protoc-gen-go.
// source: containermanagement_protocol.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	containermanagement_protocol.proto

It has these top-level messages:
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hadoop_yarn1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for ContainerManagementProtocolService service

type ContainerManagementProtocolServiceClient interface {
	StartContainers(ctx context.Context, in *hadoop_yarn1.StartContainersRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.StartContainersResponseProto, error)
	StopContainers(ctx context.Context, in *hadoop_yarn1.StopContainersRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.StopContainersResponseProto, error)
	GetContainerStatuses(ctx context.Context, in *hadoop_yarn1.GetContainerStatusesRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.GetContainerStatusesResponseProto, error)
	IncreaseContainersResource(ctx context.Context, in *hadoop_yarn1.IncreaseContainersResourceRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.IncreaseContainersResourceResponseProto, error)
	SignalToContainer(ctx context.Context, in *hadoop_yarn1.SignalContainerRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.SignalContainerResponseProto, error)
}

type containerManagementProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewContainerManagementProtocolServiceClient(cc *grpc.ClientConn) ContainerManagementProtocolServiceClient {
	return &containerManagementProtocolServiceClient{cc}
}

func (c *containerManagementProtocolServiceClient) StartContainers(ctx context.Context, in *hadoop_yarn1.StartContainersRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.StartContainersResponseProto, error) {
	out := new(hadoop_yarn1.StartContainersResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.yarn.ContainerManagementProtocolService/startContainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagementProtocolServiceClient) StopContainers(ctx context.Context, in *hadoop_yarn1.StopContainersRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.StopContainersResponseProto, error) {
	out := new(hadoop_yarn1.StopContainersResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.yarn.ContainerManagementProtocolService/stopContainers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagementProtocolServiceClient) GetContainerStatuses(ctx context.Context, in *hadoop_yarn1.GetContainerStatusesRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.GetContainerStatusesResponseProto, error) {
	out := new(hadoop_yarn1.GetContainerStatusesResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.yarn.ContainerManagementProtocolService/getContainerStatuses", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagementProtocolServiceClient) IncreaseContainersResource(ctx context.Context, in *hadoop_yarn1.IncreaseContainersResourceRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.IncreaseContainersResourceResponseProto, error) {
	out := new(hadoop_yarn1.IncreaseContainersResourceResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.yarn.ContainerManagementProtocolService/increaseContainersResource", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *containerManagementProtocolServiceClient) SignalToContainer(ctx context.Context, in *hadoop_yarn1.SignalContainerRequestProto, opts ...grpc.CallOption) (*hadoop_yarn1.SignalContainerResponseProto, error) {
	out := new(hadoop_yarn1.SignalContainerResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.yarn.ContainerManagementProtocolService/signalToContainer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ContainerManagementProtocolService service

type ContainerManagementProtocolServiceServer interface {
	StartContainers(context.Context, *hadoop_yarn1.StartContainersRequestProto) (*hadoop_yarn1.StartContainersResponseProto, error)
	StopContainers(context.Context, *hadoop_yarn1.StopContainersRequestProto) (*hadoop_yarn1.StopContainersResponseProto, error)
	GetContainerStatuses(context.Context, *hadoop_yarn1.GetContainerStatusesRequestProto) (*hadoop_yarn1.GetContainerStatusesResponseProto, error)
	IncreaseContainersResource(context.Context, *hadoop_yarn1.IncreaseContainersResourceRequestProto) (*hadoop_yarn1.IncreaseContainersResourceResponseProto, error)
	SignalToContainer(context.Context, *hadoop_yarn1.SignalContainerRequestProto) (*hadoop_yarn1.SignalContainerResponseProto, error)
}

func RegisterContainerManagementProtocolServiceServer(s *grpc.Server, srv ContainerManagementProtocolServiceServer) {
	s.RegisterService(&_ContainerManagementProtocolService_serviceDesc, srv)
}

func _ContainerManagementProtocolService_StartContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hadoop_yarn1.StartContainersRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagementProtocolServiceServer).StartContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.yarn.ContainerManagementProtocolService/StartContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagementProtocolServiceServer).StartContainers(ctx, req.(*hadoop_yarn1.StartContainersRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManagementProtocolService_StopContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hadoop_yarn1.StopContainersRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagementProtocolServiceServer).StopContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.yarn.ContainerManagementProtocolService/StopContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagementProtocolServiceServer).StopContainers(ctx, req.(*hadoop_yarn1.StopContainersRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManagementProtocolService_GetContainerStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hadoop_yarn1.GetContainerStatusesRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagementProtocolServiceServer).GetContainerStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.yarn.ContainerManagementProtocolService/GetContainerStatuses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagementProtocolServiceServer).GetContainerStatuses(ctx, req.(*hadoop_yarn1.GetContainerStatusesRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManagementProtocolService_IncreaseContainersResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hadoop_yarn1.IncreaseContainersResourceRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagementProtocolServiceServer).IncreaseContainersResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.yarn.ContainerManagementProtocolService/IncreaseContainersResource",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagementProtocolServiceServer).IncreaseContainersResource(ctx, req.(*hadoop_yarn1.IncreaseContainersResourceRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContainerManagementProtocolService_SignalToContainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(hadoop_yarn1.SignalContainerRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContainerManagementProtocolServiceServer).SignalToContainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.yarn.ContainerManagementProtocolService/SignalToContainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContainerManagementProtocolServiceServer).SignalToContainer(ctx, req.(*hadoop_yarn1.SignalContainerRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContainerManagementProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hadoop.yarn.ContainerManagementProtocolService",
	HandlerType: (*ContainerManagementProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "startContainers",
			Handler:    _ContainerManagementProtocolService_StartContainers_Handler,
		},
		{
			MethodName: "stopContainers",
			Handler:    _ContainerManagementProtocolService_StopContainers_Handler,
		},
		{
			MethodName: "getContainerStatuses",
			Handler:    _ContainerManagementProtocolService_GetContainerStatuses_Handler,
		},
		{
			MethodName: "increaseContainersResource",
			Handler:    _ContainerManagementProtocolService_IncreaseContainersResource_Handler,
		},
		{
			MethodName: "signalToContainer",
			Handler:    _ContainerManagementProtocolService_SignalToContainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("containermanagement_protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4a, 0xc4, 0x30,
	0x14, 0xc6, 0x09, 0xb8, 0x8a, 0xa0, 0x18, 0xdc, 0x58, 0x5d, 0xcd, 0xc6, 0x71, 0x61, 0x16, 0xea,
	0x05, 0x1c, 0x17, 0xe2, 0x42, 0x10, 0xc7, 0xfd, 0xf0, 0x88, 0xcf, 0xb6, 0x30, 0x93, 0x17, 0xf3,
	0x52, 0xc1, 0x13, 0xe8, 0x31, 0x3c, 0x98, 0x87, 0x71, 0x6c, 0xb5, 0x26, 0xc5, 0x09, 0xdd, 0x94,
	0xc2, 0xf7, 0xfb, 0xfe, 0x90, 0x44, 0x4e, 0x0c, 0xd9, 0x00, 0xb5, 0x45, 0xbf, 0x02, 0x0b, 0x25,
	0xae, 0xd0, 0x86, 0x85, 0xf3, 0x14, 0xc8, 0xd0, 0x52, 0xb7, 0x3f, 0x6a, 0xbb, 0x82, 0x47, 0x22,
	0xa7, 0x5f, 0xc1, 0xdb, 0xe2, 0xe0, 0xfb, 0xbb, 0x60, 0xf4, 0x2f, 0xb5, 0xc1, 0x8e, 0xe4, 0x8e,
	0x3b, 0xfb, 0xdc, 0x92, 0x93, 0xab, 0xdf, 0xb8, 0xdb, 0x3e, 0xee, 0xee, 0x27, 0x6d, 0xde, 0x79,
	0xd4, 0x93, 0xdc, 0xe5, 0x00, 0x3e, 0xf4, 0x28, 0xab, 0xa9, 0x8e, 0x2a, 0xf4, 0x3c, 0x55, 0xef,
	0xf1, 0xb9, 0x41, 0xee, 0x62, 0x8a, 0x93, 0x3c, 0xc9, 0x8e, 0x2c, 0x63, 0x8b, 0x2a, 0x23, 0x77,
	0x38, 0x90, 0x8b, 0x6a, 0x8e, 0x07, 0xe6, 0x58, 0x4c, 0x5a, 0xa6, 0x59, 0x30, 0x2e, 0x69, 0xe4,
	0x7e, 0x89, 0x7f, 0x13, 0xd6, 0x83, 0x42, 0xc3, 0xc8, 0xea, 0x34, 0x49, 0xb8, 0xfe, 0x07, 0x49,
	0x0a, 0xf5, 0x08, 0x3c, 0xae, 0x7d, 0x13, 0xb2, 0xa8, 0xad, 0xf1, 0x08, 0x8c, 0xc9, 0x34, 0x6a,
	0xfc, 0xfa, 0x88, 0xcf, 0x93, 0xb8, 0x9b, 0x8d, 0x60, 0xb2, 0xe1, 0x62, 0xb4, 0x29, 0x5e, 0x52,
	0xc9, 0x3d, 0xae, 0x4b, 0x0b, 0xcb, 0x07, 0xea, 0xd1, 0xe1, 0x7d, 0xb6, 0x7a, 0xaf, 0xe6, 0xee,
	0x73, 0x48, 0x46, 0x4d, 0xb3, 0x4b, 0x79, 0x44, 0xbe, 0xd4, 0xe0, 0xc0, 0x54, 0x98, 0xd8, 0xda,
	0xe7, 0x37, 0x3b, 0xcc, 0xbc, 0xbd, 0x77, 0x21, 0x3e, 0x84, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0x7b, 0x39, 0x18, 0x86, 0xee, 0x02, 0x00, 0x00,
}
