// Code generated by protoc-gen-go.
// source: GetUserMappingsProtocol.proto
// DO NOT EDIT!

package hproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
//  Get groups for user request.
type GetGroupsForUserRequestProto struct {
	User             *string `protobuf:"bytes,1,req,name=user" json:"user,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetGroupsForUserRequestProto) Reset()                    { *m = GetGroupsForUserRequestProto{} }
func (m *GetGroupsForUserRequestProto) String() string            { return proto.CompactTextString(m) }
func (*GetGroupsForUserRequestProto) ProtoMessage()               {}
func (*GetGroupsForUserRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GetGroupsForUserRequestProto) GetUser() string {
	if m != nil && m.User != nil {
		return *m.User
	}
	return ""
}

// *
// Response for get groups.
type GetGroupsForUserResponseProto struct {
	Groups           []string `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GetGroupsForUserResponseProto) Reset()                    { *m = GetGroupsForUserResponseProto{} }
func (m *GetGroupsForUserResponseProto) String() string            { return proto.CompactTextString(m) }
func (*GetGroupsForUserResponseProto) ProtoMessage()               {}
func (*GetGroupsForUserResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GetGroupsForUserResponseProto) GetGroups() []string {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*GetGroupsForUserRequestProto)(nil), "hadoop.common.GetGroupsForUserRequestProto")
	proto.RegisterType((*GetGroupsForUserResponseProto)(nil), "hadoop.common.GetGroupsForUserResponseProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GetUserMappingsProtocolService service

type GetUserMappingsProtocolServiceClient interface {
	// *
	// Get the groups which are mapped to the given user.
	GetGroupsForUser(ctx context.Context, in *GetGroupsForUserRequestProto, opts ...grpc.CallOption) (*GetGroupsForUserResponseProto, error)
}

type getUserMappingsProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewGetUserMappingsProtocolServiceClient(cc *grpc.ClientConn) GetUserMappingsProtocolServiceClient {
	return &getUserMappingsProtocolServiceClient{cc}
}

func (c *getUserMappingsProtocolServiceClient) GetGroupsForUser(ctx context.Context, in *GetGroupsForUserRequestProto, opts ...grpc.CallOption) (*GetGroupsForUserResponseProto, error) {
	out := new(GetGroupsForUserResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.common.GetUserMappingsProtocolService/getGroupsForUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetUserMappingsProtocolService service

type GetUserMappingsProtocolServiceServer interface {
	// *
	// Get the groups which are mapped to the given user.
	GetGroupsForUser(context.Context, *GetGroupsForUserRequestProto) (*GetGroupsForUserResponseProto, error)
}

func RegisterGetUserMappingsProtocolServiceServer(s *grpc.Server, srv GetUserMappingsProtocolServiceServer) {
	s.RegisterService(&_GetUserMappingsProtocolService_serviceDesc, srv)
}

func _GetUserMappingsProtocolService_GetGroupsForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupsForUserRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetUserMappingsProtocolServiceServer).GetGroupsForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.common.GetUserMappingsProtocolService/GetGroupsForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetUserMappingsProtocolServiceServer).GetGroupsForUser(ctx, req.(*GetGroupsForUserRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetUserMappingsProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hadoop.common.GetUserMappingsProtocolService",
	HandlerType: (*GetUserMappingsProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getGroupsForUser",
			Handler:    _GetUserMappingsProtocolService_GetGroupsForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor2,
}

func init() { proto.RegisterFile("GetUserMappingsProtocol.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 209 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x75, 0x4f, 0x2d, 0x09,
	0x2d, 0x4e, 0x2d, 0xf2, 0x4d, 0x2c, 0x28, 0xc8, 0xcc, 0x4b, 0x2f, 0x0e, 0x28, 0xca, 0x2f, 0xc9,
	0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x00, 0x31, 0x84, 0x78, 0x33, 0x12, 0x53, 0xf2, 0xf3, 0x0b, 0xf4,
	0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x94, 0x8c, 0xb8, 0x64, 0x80, 0xea, 0xdd, 0x8b, 0xf2, 0x4b,
	0x0b, 0x8a, 0xdd, 0xf2, 0x8b, 0x40, 0x1a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xc0, 0xfa,
	0x84, 0x84, 0xb8, 0x58, 0x4a, 0x81, 0x62, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x92, 0x39, 0xd8, 0x0e, 0x34, 0x3d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x10, 0x4d, 0x62, 0x5c,
	0x6c, 0xe9, 0x60, 0x59, 0xa0, 0x36, 0x66, 0xa0, 0x36, 0x28, 0xcf, 0xa8, 0x9f, 0x91, 0x4b, 0x0e,
	0x87, 0xeb, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x72, 0xb9, 0x04, 0xd2, 0xd1, 0xcc,
	0x16, 0xd2, 0xd6, 0x43, 0x71, 0xb3, 0x1e, 0x3e, 0x07, 0x4b, 0xe9, 0x10, 0x54, 0x8c, 0xe4, 0x52,
	0x27, 0x17, 0x2e, 0xd9, 0xfc, 0xa2, 0x74, 0xbd, 0xc4, 0x82, 0xc4, 0xe4, 0x8c, 0x54, 0x98, 0xce,
	0x92, 0xfc, 0xfc, 0x9c, 0x62, 0x48, 0x70, 0x39, 0xe1, 0x0a, 0x4d, 0x30, 0x5d, 0xdc, 0xc1, 0xc8,
	0xb8, 0x80, 0x91, 0x11, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x38, 0xcc, 0x6f, 0x73, 0x01, 0x00,
	0x00,
}
