// Code generated by protoc-gen-go.
// source: RefreshCallQueueProtocol.proto
// DO NOT EDIT!

package hproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// *
//  Refresh callqueue request.
type RefreshCallQueueRequestProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshCallQueueRequestProto) Reset()                    { *m = RefreshCallQueueRequestProto{} }
func (m *RefreshCallQueueRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshCallQueueRequestProto) ProtoMessage()               {}
func (*RefreshCallQueueRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{0} }

// *
// void response.
type RefreshCallQueueResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *RefreshCallQueueResponseProto) Reset()                    { *m = RefreshCallQueueResponseProto{} }
func (m *RefreshCallQueueResponseProto) String() string            { return proto.CompactTextString(m) }
func (*RefreshCallQueueResponseProto) ProtoMessage()               {}
func (*RefreshCallQueueResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor10, []int{1} }

func init() {
	proto.RegisterType((*RefreshCallQueueRequestProto)(nil), "hadoop.common.RefreshCallQueueRequestProto")
	proto.RegisterType((*RefreshCallQueueResponseProto)(nil), "hadoop.common.RefreshCallQueueResponseProto")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for RefreshCallQueueProtocolService service

type RefreshCallQueueProtocolServiceClient interface {
	// *
	// Refresh the callqueue.
	RefreshCallQueue(ctx context.Context, in *RefreshCallQueueRequestProto, opts ...grpc.CallOption) (*RefreshCallQueueResponseProto, error)
}

type refreshCallQueueProtocolServiceClient struct {
	cc *grpc.ClientConn
}

func NewRefreshCallQueueProtocolServiceClient(cc *grpc.ClientConn) RefreshCallQueueProtocolServiceClient {
	return &refreshCallQueueProtocolServiceClient{cc}
}

func (c *refreshCallQueueProtocolServiceClient) RefreshCallQueue(ctx context.Context, in *RefreshCallQueueRequestProto, opts ...grpc.CallOption) (*RefreshCallQueueResponseProto, error) {
	out := new(RefreshCallQueueResponseProto)
	err := grpc.Invoke(ctx, "/hadoop.common.RefreshCallQueueProtocolService/refreshCallQueue", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RefreshCallQueueProtocolService service

type RefreshCallQueueProtocolServiceServer interface {
	// *
	// Refresh the callqueue.
	RefreshCallQueue(context.Context, *RefreshCallQueueRequestProto) (*RefreshCallQueueResponseProto, error)
}

func RegisterRefreshCallQueueProtocolServiceServer(s *grpc.Server, srv RefreshCallQueueProtocolServiceServer) {
	s.RegisterService(&_RefreshCallQueueProtocolService_serviceDesc, srv)
}

func _RefreshCallQueueProtocolService_RefreshCallQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshCallQueueRequestProto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefreshCallQueueProtocolServiceServer).RefreshCallQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hadoop.common.RefreshCallQueueProtocolService/RefreshCallQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefreshCallQueueProtocolServiceServer).RefreshCallQueue(ctx, req.(*RefreshCallQueueRequestProto))
	}
	return interceptor(ctx, in, info, handler)
}

var _RefreshCallQueueProtocolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hadoop.common.RefreshCallQueueProtocolService",
	HandlerType: (*RefreshCallQueueProtocolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "refreshCallQueue",
			Handler:    _RefreshCallQueueProtocolService_RefreshCallQueue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor10,
}

func init() { proto.RegisterFile("RefreshCallQueueProtocol.proto", fileDescriptor10) }

var fileDescriptor10 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x0b, 0x4a, 0x4d, 0x2b,
	0x4a, 0x2d, 0xce, 0x70, 0x4e, 0xcc, 0xc9, 0x09, 0x2c, 0x4d, 0x2d, 0x4d, 0x0d, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2b, 0x00, 0x31, 0x84, 0x78, 0x33, 0x12, 0x53, 0xf2, 0xf3, 0x0b,
	0xf4, 0x92, 0xf3, 0x73, 0x73, 0xf3, 0xf3, 0x94, 0xe4, 0xb8, 0x64, 0xd0, 0x35, 0x04, 0xa5, 0x16,
	0x96, 0xa6, 0x16, 0x97, 0x80, 0xf5, 0x29, 0xc9, 0x73, 0xc9, 0x62, 0xca, 0x17, 0x17, 0xe4, 0xe7,
	0x15, 0x43, 0x0c, 0x36, 0x9a, 0xc0, 0xc8, 0x25, 0x8f, 0xcb, 0xca, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc,
	0xe4, 0x54, 0xa1, 0x5c, 0x2e, 0x81, 0x22, 0x34, 0x25, 0x42, 0xda, 0x7a, 0x28, 0x0e, 0xd1, 0xc3,
	0xe7, 0x0a, 0x29, 0x1d, 0x82, 0x8a, 0x91, 0x9c, 0xe4, 0xe4, 0xcc, 0x25, 0x9d, 0x5f, 0x94, 0xae,
	0x97, 0x58, 0x90, 0x98, 0x9c, 0x91, 0x0a, 0xd3, 0x99, 0x59, 0x90, 0x0c, 0x09, 0x01, 0x27, 0x9c,
	0x21, 0x04, 0xa6, 0x8b, 0x3b, 0x18, 0x19, 0x17, 0x30, 0x32, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x5d, 0x22, 0xcd, 0xe0, 0x48, 0x01, 0x00, 0x00,
}
