// Code generated by protoc-gen-go.
// source: yarn_server_common_service_protos.proto
// DO NOT EDIT!

package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import hadoop_yarn "."
import hadoop_yarn1 "."

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DistSchedRegisterResponseProto struct {
	RegisterResponse             *hadoop_yarn1.RegisterApplicationMasterResponseProto `protobuf:"bytes,1,opt,name=register_response,json=registerResponse" json:"register_response,omitempty"`
	MaxAllocCapability           *hadoop_yarn.ResourceProto                           `protobuf:"bytes,2,opt,name=max_alloc_capability,json=maxAllocCapability" json:"max_alloc_capability,omitempty"`
	MinAllocCapability           *hadoop_yarn.ResourceProto                           `protobuf:"bytes,3,opt,name=min_alloc_capability,json=minAllocCapability" json:"min_alloc_capability,omitempty"`
	IncrAllocCapability          *hadoop_yarn.ResourceProto                           `protobuf:"bytes,4,opt,name=incr_alloc_capability,json=incrAllocCapability" json:"incr_alloc_capability,omitempty"`
	ContainerTokenExpiryInterval *int32                                               `protobuf:"varint,5,opt,name=container_token_expiry_interval,json=containerTokenExpiryInterval" json:"container_token_expiry_interval,omitempty"`
	ContainerIdStart             *int64                                               `protobuf:"varint,6,opt,name=container_id_start,json=containerIdStart" json:"container_id_start,omitempty"`
	NodesForScheduling           []*hadoop_yarn.NodeIdProto                           `protobuf:"bytes,7,rep,name=nodes_for_scheduling,json=nodesForScheduling" json:"nodes_for_scheduling,omitempty"`
	XXX_unrecognized             []byte                                               `json:"-"`
}

func (m *DistSchedRegisterResponseProto) Reset()                    { *m = DistSchedRegisterResponseProto{} }
func (m *DistSchedRegisterResponseProto) String() string            { return proto.CompactTextString(m) }
func (*DistSchedRegisterResponseProto) ProtoMessage()               {}
func (*DistSchedRegisterResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DistSchedRegisterResponseProto) GetRegisterResponse() *hadoop_yarn1.RegisterApplicationMasterResponseProto {
	if m != nil {
		return m.RegisterResponse
	}
	return nil
}

func (m *DistSchedRegisterResponseProto) GetMaxAllocCapability() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.MaxAllocCapability
	}
	return nil
}

func (m *DistSchedRegisterResponseProto) GetMinAllocCapability() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.MinAllocCapability
	}
	return nil
}

func (m *DistSchedRegisterResponseProto) GetIncrAllocCapability() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.IncrAllocCapability
	}
	return nil
}

func (m *DistSchedRegisterResponseProto) GetContainerTokenExpiryInterval() int32 {
	if m != nil && m.ContainerTokenExpiryInterval != nil {
		return *m.ContainerTokenExpiryInterval
	}
	return 0
}

func (m *DistSchedRegisterResponseProto) GetContainerIdStart() int64 {
	if m != nil && m.ContainerIdStart != nil {
		return *m.ContainerIdStart
	}
	return 0
}

func (m *DistSchedRegisterResponseProto) GetNodesForScheduling() []*hadoop_yarn.NodeIdProto {
	if m != nil {
		return m.NodesForScheduling
	}
	return nil
}

type DistSchedAllocateResponseProto struct {
	AllocateResponse   *hadoop_yarn1.AllocateResponseProto `protobuf:"bytes,1,opt,name=allocate_response,json=allocateResponse" json:"allocate_response,omitempty"`
	NodesForScheduling []*hadoop_yarn.NodeIdProto          `protobuf:"bytes,2,rep,name=nodes_for_scheduling,json=nodesForScheduling" json:"nodes_for_scheduling,omitempty"`
	XXX_unrecognized   []byte                              `json:"-"`
}

func (m *DistSchedAllocateResponseProto) Reset()                    { *m = DistSchedAllocateResponseProto{} }
func (m *DistSchedAllocateResponseProto) String() string            { return proto.CompactTextString(m) }
func (*DistSchedAllocateResponseProto) ProtoMessage()               {}
func (*DistSchedAllocateResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DistSchedAllocateResponseProto) GetAllocateResponse() *hadoop_yarn1.AllocateResponseProto {
	if m != nil {
		return m.AllocateResponse
	}
	return nil
}

func (m *DistSchedAllocateResponseProto) GetNodesForScheduling() []*hadoop_yarn.NodeIdProto {
	if m != nil {
		return m.NodesForScheduling
	}
	return nil
}

type DistSchedAllocateRequestProto struct {
	AllocateRequest     *hadoop_yarn1.AllocateRequestProto `protobuf:"bytes,1,opt,name=allocate_request,json=allocateRequest" json:"allocate_request,omitempty"`
	AllocatedContainers []*hadoop_yarn.ContainerProto      `protobuf:"bytes,2,rep,name=allocated_containers,json=allocatedContainers" json:"allocated_containers,omitempty"`
	XXX_unrecognized    []byte                             `json:"-"`
}

func (m *DistSchedAllocateRequestProto) Reset()                    { *m = DistSchedAllocateRequestProto{} }
func (m *DistSchedAllocateRequestProto) String() string            { return proto.CompactTextString(m) }
func (*DistSchedAllocateRequestProto) ProtoMessage()               {}
func (*DistSchedAllocateRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *DistSchedAllocateRequestProto) GetAllocateRequest() *hadoop_yarn1.AllocateRequestProto {
	if m != nil {
		return m.AllocateRequest
	}
	return nil
}

func (m *DistSchedAllocateRequestProto) GetAllocatedContainers() []*hadoop_yarn.ContainerProto {
	if m != nil {
		return m.AllocatedContainers
	}
	return nil
}

type NodeLabelsProto struct {
	NodeLabels       []*hadoop_yarn.NodeLabelProto `protobuf:"bytes,1,rep,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *NodeLabelsProto) Reset()                    { *m = NodeLabelsProto{} }
func (m *NodeLabelsProto) String() string            { return proto.CompactTextString(m) }
func (*NodeLabelsProto) ProtoMessage()               {}
func (*NodeLabelsProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *NodeLabelsProto) GetNodeLabels() []*hadoop_yarn.NodeLabelProto {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type RegisterNodeManagerRequestProto struct {
	NodeId              *hadoop_yarn.NodeIdProto          `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	HttpPort            *int32                            `protobuf:"varint,3,opt,name=http_port,json=httpPort" json:"http_port,omitempty"`
	Resource            *hadoop_yarn.ResourceProto        `protobuf:"bytes,4,opt,name=resource" json:"resource,omitempty"`
	NmVersion           *string                           `protobuf:"bytes,5,opt,name=nm_version,json=nmVersion" json:"nm_version,omitempty"`
	ContainerStatuses   []*NMContainerStatusProto         `protobuf:"bytes,6,rep,name=container_statuses,json=containerStatuses" json:"container_statuses,omitempty"`
	RunningApplications []*hadoop_yarn.ApplicationIdProto `protobuf:"bytes,7,rep,name=runningApplications" json:"runningApplications,omitempty"`
	NodeLabels          *NodeLabelsProto                  `protobuf:"bytes,8,opt,name=nodeLabels" json:"nodeLabels,omitempty"`
	XXX_unrecognized    []byte                            `json:"-"`
}

func (m *RegisterNodeManagerRequestProto) Reset()                    { *m = RegisterNodeManagerRequestProto{} }
func (m *RegisterNodeManagerRequestProto) String() string            { return proto.CompactTextString(m) }
func (*RegisterNodeManagerRequestProto) ProtoMessage()               {}
func (*RegisterNodeManagerRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *RegisterNodeManagerRequestProto) GetNodeId() *hadoop_yarn.NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

func (m *RegisterNodeManagerRequestProto) GetHttpPort() int32 {
	if m != nil && m.HttpPort != nil {
		return *m.HttpPort
	}
	return 0
}

func (m *RegisterNodeManagerRequestProto) GetResource() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *RegisterNodeManagerRequestProto) GetNmVersion() string {
	if m != nil && m.NmVersion != nil {
		return *m.NmVersion
	}
	return ""
}

func (m *RegisterNodeManagerRequestProto) GetContainerStatuses() []*NMContainerStatusProto {
	if m != nil {
		return m.ContainerStatuses
	}
	return nil
}

func (m *RegisterNodeManagerRequestProto) GetRunningApplications() []*hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.RunningApplications
	}
	return nil
}

func (m *RegisterNodeManagerRequestProto) GetNodeLabels() *NodeLabelsProto {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

type RegisterNodeManagerResponseProto struct {
	ContainerTokenMasterKey   *MasterKeyProto            `protobuf:"bytes,1,opt,name=container_token_master_key,json=containerTokenMasterKey" json:"container_token_master_key,omitempty"`
	NmTokenMasterKey          *MasterKeyProto            `protobuf:"bytes,2,opt,name=nm_token_master_key,json=nmTokenMasterKey" json:"nm_token_master_key,omitempty"`
	NodeAction                *NodeActionProto           `protobuf:"varint,3,opt,name=nodeAction,enum=hadoop.yarn.NodeActionProto" json:"nodeAction,omitempty"`
	RmIdentifier              *int64                     `protobuf:"varint,4,opt,name=rm_identifier,json=rmIdentifier" json:"rm_identifier,omitempty"`
	DiagnosticsMessage        *string                    `protobuf:"bytes,5,opt,name=diagnostics_message,json=diagnosticsMessage" json:"diagnostics_message,omitempty"`
	RmVersion                 *string                    `protobuf:"bytes,6,opt,name=rm_version,json=rmVersion" json:"rm_version,omitempty"`
	AreNodeLabelsAcceptedByRM *bool                      `protobuf:"varint,7,opt,name=areNodeLabelsAcceptedByRM,def=0" json:"areNodeLabelsAcceptedByRM,omitempty"`
	Resource                  *hadoop_yarn.ResourceProto `protobuf:"bytes,8,opt,name=resource" json:"resource,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *RegisterNodeManagerResponseProto) Reset()         { *m = RegisterNodeManagerResponseProto{} }
func (m *RegisterNodeManagerResponseProto) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeManagerResponseProto) ProtoMessage()    {}
func (*RegisterNodeManagerResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{5}
}

const Default_RegisterNodeManagerResponseProto_AreNodeLabelsAcceptedByRM bool = false

func (m *RegisterNodeManagerResponseProto) GetContainerTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.ContainerTokenMasterKey
	}
	return nil
}

func (m *RegisterNodeManagerResponseProto) GetNmTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.NmTokenMasterKey
	}
	return nil
}

func (m *RegisterNodeManagerResponseProto) GetNodeAction() NodeActionProto {
	if m != nil && m.NodeAction != nil {
		return *m.NodeAction
	}
	return NodeActionProto_NORMAL
}

func (m *RegisterNodeManagerResponseProto) GetRmIdentifier() int64 {
	if m != nil && m.RmIdentifier != nil {
		return *m.RmIdentifier
	}
	return 0
}

func (m *RegisterNodeManagerResponseProto) GetDiagnosticsMessage() string {
	if m != nil && m.DiagnosticsMessage != nil {
		return *m.DiagnosticsMessage
	}
	return ""
}

func (m *RegisterNodeManagerResponseProto) GetRmVersion() string {
	if m != nil && m.RmVersion != nil {
		return *m.RmVersion
	}
	return ""
}

func (m *RegisterNodeManagerResponseProto) GetAreNodeLabelsAcceptedByRM() bool {
	if m != nil && m.AreNodeLabelsAcceptedByRM != nil {
		return *m.AreNodeLabelsAcceptedByRM
	}
	return Default_RegisterNodeManagerResponseProto_AreNodeLabelsAcceptedByRM
}

func (m *RegisterNodeManagerResponseProto) GetResource() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

type UnRegisterNodeManagerRequestProto struct {
	NodeId           *hadoop_yarn.NodeIdProto `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *UnRegisterNodeManagerRequestProto) Reset()         { *m = UnRegisterNodeManagerRequestProto{} }
func (m *UnRegisterNodeManagerRequestProto) String() string { return proto.CompactTextString(m) }
func (*UnRegisterNodeManagerRequestProto) ProtoMessage()    {}
func (*UnRegisterNodeManagerRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{6}
}

func (m *UnRegisterNodeManagerRequestProto) GetNodeId() *hadoop_yarn.NodeIdProto {
	if m != nil {
		return m.NodeId
	}
	return nil
}

type UnRegisterNodeManagerResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnRegisterNodeManagerResponseProto) Reset()         { *m = UnRegisterNodeManagerResponseProto{} }
func (m *UnRegisterNodeManagerResponseProto) String() string { return proto.CompactTextString(m) }
func (*UnRegisterNodeManagerResponseProto) ProtoMessage()    {}
func (*UnRegisterNodeManagerResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{7}
}

type NodeHeartbeatRequestProto struct {
	NodeStatus                       *NodeStatusProto             `protobuf:"bytes,1,opt,name=node_status,json=nodeStatus" json:"node_status,omitempty"`
	LastKnownContainerTokenMasterKey *MasterKeyProto              `protobuf:"bytes,2,opt,name=last_known_container_token_master_key,json=lastKnownContainerTokenMasterKey" json:"last_known_container_token_master_key,omitempty"`
	LastKnownNmTokenMasterKey        *MasterKeyProto              `protobuf:"bytes,3,opt,name=last_known_nm_token_master_key,json=lastKnownNmTokenMasterKey" json:"last_known_nm_token_master_key,omitempty"`
	NodeLabels                       *NodeLabelsProto             `protobuf:"bytes,4,opt,name=nodeLabels" json:"nodeLabels,omitempty"`
	LogAggregationReportsForApps     []*LogAggregationReportProto `protobuf:"bytes,5,rep,name=log_aggregation_reports_for_apps,json=logAggregationReportsForApps" json:"log_aggregation_reports_for_apps,omitempty"`
	RegisteredCollectors             []*AppCollectorsMapProto     `protobuf:"bytes,6,rep,name=registered_collectors,json=registeredCollectors" json:"registered_collectors,omitempty"`
	XXX_unrecognized                 []byte                       `json:"-"`
}

func (m *NodeHeartbeatRequestProto) Reset()                    { *m = NodeHeartbeatRequestProto{} }
func (m *NodeHeartbeatRequestProto) String() string            { return proto.CompactTextString(m) }
func (*NodeHeartbeatRequestProto) ProtoMessage()               {}
func (*NodeHeartbeatRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *NodeHeartbeatRequestProto) GetNodeStatus() *NodeStatusProto {
	if m != nil {
		return m.NodeStatus
	}
	return nil
}

func (m *NodeHeartbeatRequestProto) GetLastKnownContainerTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.LastKnownContainerTokenMasterKey
	}
	return nil
}

func (m *NodeHeartbeatRequestProto) GetLastKnownNmTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.LastKnownNmTokenMasterKey
	}
	return nil
}

func (m *NodeHeartbeatRequestProto) GetNodeLabels() *NodeLabelsProto {
	if m != nil {
		return m.NodeLabels
	}
	return nil
}

func (m *NodeHeartbeatRequestProto) GetLogAggregationReportsForApps() []*LogAggregationReportProto {
	if m != nil {
		return m.LogAggregationReportsForApps
	}
	return nil
}

func (m *NodeHeartbeatRequestProto) GetRegisteredCollectors() []*AppCollectorsMapProto {
	if m != nil {
		return m.RegisteredCollectors
	}
	return nil
}

type LogAggregationReportProto struct {
	ApplicationId        *hadoop_yarn.ApplicationIdProto        `protobuf:"bytes,1,opt,name=application_id,json=applicationId" json:"application_id,omitempty"`
	LogAggregationStatus *hadoop_yarn.LogAggregationStatusProto `protobuf:"varint,2,opt,name=log_aggregation_status,json=logAggregationStatus,enum=hadoop.yarn.LogAggregationStatusProto" json:"log_aggregation_status,omitempty"`
	Diagnostics          *string                                `protobuf:"bytes,3,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	XXX_unrecognized     []byte                                 `json:"-"`
}

func (m *LogAggregationReportProto) Reset()                    { *m = LogAggregationReportProto{} }
func (m *LogAggregationReportProto) String() string            { return proto.CompactTextString(m) }
func (*LogAggregationReportProto) ProtoMessage()               {}
func (*LogAggregationReportProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

const Default_LogAggregationReportProto_Diagnostics string = "N/A"

func (m *LogAggregationReportProto) GetApplicationId() *hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.ApplicationId
	}
	return nil
}

func (m *LogAggregationReportProto) GetLogAggregationStatus() hadoop_yarn.LogAggregationStatusProto {
	if m != nil && m.LogAggregationStatus != nil {
		return *m.LogAggregationStatus
	}
	return hadoop_yarn.LogAggregationStatusProto_LOG_DISABLED
}

func (m *LogAggregationReportProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_LogAggregationReportProto_Diagnostics
}

type NodeHeartbeatResponseProto struct {
	ResponseId                  *int32                                      `protobuf:"varint,1,opt,name=response_id,json=responseId" json:"response_id,omitempty"`
	ContainerTokenMasterKey     *MasterKeyProto                             `protobuf:"bytes,2,opt,name=container_token_master_key,json=containerTokenMasterKey" json:"container_token_master_key,omitempty"`
	NmTokenMasterKey            *MasterKeyProto                             `protobuf:"bytes,3,opt,name=nm_token_master_key,json=nmTokenMasterKey" json:"nm_token_master_key,omitempty"`
	NodeAction                  *NodeActionProto                            `protobuf:"varint,4,opt,name=nodeAction,enum=hadoop.yarn.NodeActionProto" json:"nodeAction,omitempty"`
	ContainersToCleanup         []*hadoop_yarn.ContainerIdProto             `protobuf:"bytes,5,rep,name=containers_to_cleanup,json=containersToCleanup" json:"containers_to_cleanup,omitempty"`
	ApplicationsToCleanup       []*hadoop_yarn.ApplicationIdProto           `protobuf:"bytes,6,rep,name=applications_to_cleanup,json=applicationsToCleanup" json:"applications_to_cleanup,omitempty"`
	NextHeartBeatInterval       *int64                                      `protobuf:"varint,7,opt,name=nextHeartBeatInterval" json:"nextHeartBeatInterval,omitempty"`
	DiagnosticsMessage          *string                                     `protobuf:"bytes,8,opt,name=diagnostics_message,json=diagnosticsMessage" json:"diagnostics_message,omitempty"`
	ContainersToBeRemovedFromNm []*hadoop_yarn.ContainerIdProto             `protobuf:"bytes,9,rep,name=containers_to_be_removed_from_nm,json=containersToBeRemovedFromNm" json:"containers_to_be_removed_from_nm,omitempty"`
	SystemCredentialsForApps    []*SystemCredentialsForAppsProto            `protobuf:"bytes,10,rep,name=system_credentials_for_apps,json=systemCredentialsForApps" json:"system_credentials_for_apps,omitempty"`
	AreNodeLabelsAcceptedByRM   *bool                                       `protobuf:"varint,11,opt,name=areNodeLabelsAcceptedByRM,def=0" json:"areNodeLabelsAcceptedByRM,omitempty"`
	ContainersToDecrease        []*hadoop_yarn.ContainerProto               `protobuf:"bytes,12,rep,name=containers_to_decrease,json=containersToDecrease" json:"containers_to_decrease,omitempty"`
	ContainersToSignal          []*hadoop_yarn1.SignalContainerRequestProto `protobuf:"bytes,13,rep,name=containers_to_signal,json=containersToSignal" json:"containers_to_signal,omitempty"`
	Resource                    *hadoop_yarn.ResourceProto                  `protobuf:"bytes,14,opt,name=resource" json:"resource,omitempty"`
	ContainerQueuingLimit       *ContainerQueuingLimitProto                 `protobuf:"bytes,15,opt,name=container_queuing_limit,json=containerQueuingLimit" json:"container_queuing_limit,omitempty"`
	AppCollectorsMap            []*AppCollectorsMapProto                    `protobuf:"bytes,16,rep,name=app_collectors_map,json=appCollectorsMap" json:"app_collectors_map,omitempty"`
	XXX_unrecognized            []byte                                      `json:"-"`
}

func (m *NodeHeartbeatResponseProto) Reset()                    { *m = NodeHeartbeatResponseProto{} }
func (m *NodeHeartbeatResponseProto) String() string            { return proto.CompactTextString(m) }
func (*NodeHeartbeatResponseProto) ProtoMessage()               {}
func (*NodeHeartbeatResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

const Default_NodeHeartbeatResponseProto_AreNodeLabelsAcceptedByRM bool = false

func (m *NodeHeartbeatResponseProto) GetResponseId() int32 {
	if m != nil && m.ResponseId != nil {
		return *m.ResponseId
	}
	return 0
}

func (m *NodeHeartbeatResponseProto) GetContainerTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.ContainerTokenMasterKey
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetNmTokenMasterKey() *MasterKeyProto {
	if m != nil {
		return m.NmTokenMasterKey
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetNodeAction() NodeActionProto {
	if m != nil && m.NodeAction != nil {
		return *m.NodeAction
	}
	return NodeActionProto_NORMAL
}

func (m *NodeHeartbeatResponseProto) GetContainersToCleanup() []*hadoop_yarn.ContainerIdProto {
	if m != nil {
		return m.ContainersToCleanup
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetApplicationsToCleanup() []*hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.ApplicationsToCleanup
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetNextHeartBeatInterval() int64 {
	if m != nil && m.NextHeartBeatInterval != nil {
		return *m.NextHeartBeatInterval
	}
	return 0
}

func (m *NodeHeartbeatResponseProto) GetDiagnosticsMessage() string {
	if m != nil && m.DiagnosticsMessage != nil {
		return *m.DiagnosticsMessage
	}
	return ""
}

func (m *NodeHeartbeatResponseProto) GetContainersToBeRemovedFromNm() []*hadoop_yarn.ContainerIdProto {
	if m != nil {
		return m.ContainersToBeRemovedFromNm
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetSystemCredentialsForApps() []*SystemCredentialsForAppsProto {
	if m != nil {
		return m.SystemCredentialsForApps
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetAreNodeLabelsAcceptedByRM() bool {
	if m != nil && m.AreNodeLabelsAcceptedByRM != nil {
		return *m.AreNodeLabelsAcceptedByRM
	}
	return Default_NodeHeartbeatResponseProto_AreNodeLabelsAcceptedByRM
}

func (m *NodeHeartbeatResponseProto) GetContainersToDecrease() []*hadoop_yarn.ContainerProto {
	if m != nil {
		return m.ContainersToDecrease
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetContainersToSignal() []*hadoop_yarn1.SignalContainerRequestProto {
	if m != nil {
		return m.ContainersToSignal
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetResource() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetContainerQueuingLimit() *ContainerQueuingLimitProto {
	if m != nil {
		return m.ContainerQueuingLimit
	}
	return nil
}

func (m *NodeHeartbeatResponseProto) GetAppCollectorsMap() []*AppCollectorsMapProto {
	if m != nil {
		return m.AppCollectorsMap
	}
	return nil
}

type ContainerQueuingLimitProto struct {
	MaxQueueLength       *int32 `protobuf:"varint,1,opt,name=max_queue_length,json=maxQueueLength" json:"max_queue_length,omitempty"`
	MaxQueueWaitTimeInMs *int32 `protobuf:"varint,2,opt,name=max_queue_wait_time_in_ms,json=maxQueueWaitTimeInMs" json:"max_queue_wait_time_in_ms,omitempty"`
	XXX_unrecognized     []byte `json:"-"`
}

func (m *ContainerQueuingLimitProto) Reset()                    { *m = ContainerQueuingLimitProto{} }
func (m *ContainerQueuingLimitProto) String() string            { return proto.CompactTextString(m) }
func (*ContainerQueuingLimitProto) ProtoMessage()               {}
func (*ContainerQueuingLimitProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *ContainerQueuingLimitProto) GetMaxQueueLength() int32 {
	if m != nil && m.MaxQueueLength != nil {
		return *m.MaxQueueLength
	}
	return 0
}

func (m *ContainerQueuingLimitProto) GetMaxQueueWaitTimeInMs() int32 {
	if m != nil && m.MaxQueueWaitTimeInMs != nil {
		return *m.MaxQueueWaitTimeInMs
	}
	return 0
}

type SystemCredentialsForAppsProto struct {
	AppId             *hadoop_yarn.ApplicationIdProto `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	CredentialsForApp []byte                          `protobuf:"bytes,2,opt,name=credentialsForApp" json:"credentialsForApp,omitempty"`
	XXX_unrecognized  []byte                          `json:"-"`
}

func (m *SystemCredentialsForAppsProto) Reset()                    { *m = SystemCredentialsForAppsProto{} }
func (m *SystemCredentialsForAppsProto) String() string            { return proto.CompactTextString(m) }
func (*SystemCredentialsForAppsProto) ProtoMessage()               {}
func (*SystemCredentialsForAppsProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *SystemCredentialsForAppsProto) GetAppId() *hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *SystemCredentialsForAppsProto) GetCredentialsForApp() []byte {
	if m != nil {
		return m.CredentialsForApp
	}
	return nil
}

// //////////////////////////////////////////////////////////////////////
// //// From collector_nodemanager_protocol ////////////////////////////
// //////////////////////////////////////////////////////////////////////
type AppCollectorsMapProto struct {
	AppId            *hadoop_yarn.ApplicationIdProto `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	AppCollectorAddr *string                         `protobuf:"bytes,2,opt,name=appCollectorAddr" json:"appCollectorAddr,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *AppCollectorsMapProto) Reset()                    { *m = AppCollectorsMapProto{} }
func (m *AppCollectorsMapProto) String() string            { return proto.CompactTextString(m) }
func (*AppCollectorsMapProto) ProtoMessage()               {}
func (*AppCollectorsMapProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *AppCollectorsMapProto) GetAppId() *hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.AppId
	}
	return nil
}

func (m *AppCollectorsMapProto) GetAppCollectorAddr() string {
	if m != nil && m.AppCollectorAddr != nil {
		return *m.AppCollectorAddr
	}
	return ""
}

// ////////////////////////////////////////////////////
// ///// collector_nodemanager_protocol //////////////
// ////////////////////////////////////////////////////
type ReportNewCollectorInfoRequestProto struct {
	AppCollectors    []*AppCollectorsMapProto `protobuf:"bytes,1,rep,name=app_collectors,json=appCollectors" json:"app_collectors,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *ReportNewCollectorInfoRequestProto) Reset()         { *m = ReportNewCollectorInfoRequestProto{} }
func (m *ReportNewCollectorInfoRequestProto) String() string { return proto.CompactTextString(m) }
func (*ReportNewCollectorInfoRequestProto) ProtoMessage()    {}
func (*ReportNewCollectorInfoRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{14}
}

func (m *ReportNewCollectorInfoRequestProto) GetAppCollectors() []*AppCollectorsMapProto {
	if m != nil {
		return m.AppCollectors
	}
	return nil
}

type ReportNewCollectorInfoResponseProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ReportNewCollectorInfoResponseProto) Reset()         { *m = ReportNewCollectorInfoResponseProto{} }
func (m *ReportNewCollectorInfoResponseProto) String() string { return proto.CompactTextString(m) }
func (*ReportNewCollectorInfoResponseProto) ProtoMessage()    {}
func (*ReportNewCollectorInfoResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{15}
}

type GetTimelineCollectorContextRequestProto struct {
	AppId            *hadoop_yarn.ApplicationIdProto `protobuf:"bytes,1,opt,name=appId" json:"appId,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *GetTimelineCollectorContextRequestProto) Reset() {
	*m = GetTimelineCollectorContextRequestProto{}
}
func (m *GetTimelineCollectorContextRequestProto) String() string { return proto.CompactTextString(m) }
func (*GetTimelineCollectorContextRequestProto) ProtoMessage()    {}
func (*GetTimelineCollectorContextRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{16}
}

func (m *GetTimelineCollectorContextRequestProto) GetAppId() *hadoop_yarn.ApplicationIdProto {
	if m != nil {
		return m.AppId
	}
	return nil
}

type GetTimelineCollectorContextResponseProto struct {
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	FlowName         *string `protobuf:"bytes,2,opt,name=flow_name,json=flowName" json:"flow_name,omitempty"`
	FlowVersion      *string `protobuf:"bytes,3,opt,name=flow_version,json=flowVersion" json:"flow_version,omitempty"`
	FlowRunId        *int64  `protobuf:"varint,4,opt,name=flow_run_id,json=flowRunId" json:"flow_run_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetTimelineCollectorContextResponseProto) Reset() {
	*m = GetTimelineCollectorContextResponseProto{}
}
func (m *GetTimelineCollectorContextResponseProto) String() string { return proto.CompactTextString(m) }
func (*GetTimelineCollectorContextResponseProto) ProtoMessage()    {}
func (*GetTimelineCollectorContextResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{17}
}

func (m *GetTimelineCollectorContextResponseProto) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GetTimelineCollectorContextResponseProto) GetFlowName() string {
	if m != nil && m.FlowName != nil {
		return *m.FlowName
	}
	return ""
}

func (m *GetTimelineCollectorContextResponseProto) GetFlowVersion() string {
	if m != nil && m.FlowVersion != nil {
		return *m.FlowVersion
	}
	return ""
}

func (m *GetTimelineCollectorContextResponseProto) GetFlowRunId() int64 {
	if m != nil && m.FlowRunId != nil {
		return *m.FlowRunId
	}
	return 0
}

type NMContainerStatusProto struct {
	ContainerId         *hadoop_yarn.ContainerIdProto    `protobuf:"bytes,1,opt,name=container_id,json=containerId" json:"container_id,omitempty"`
	ContainerState      *hadoop_yarn.ContainerStateProto `protobuf:"varint,2,opt,name=container_state,json=containerState,enum=hadoop.yarn.ContainerStateProto" json:"container_state,omitempty"`
	Resource            *hadoop_yarn.ResourceProto       `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Priority            *hadoop_yarn.PriorityProto       `protobuf:"bytes,4,opt,name=priority" json:"priority,omitempty"`
	Diagnostics         *string                          `protobuf:"bytes,5,opt,name=diagnostics,def=N/A" json:"diagnostics,omitempty"`
	ContainerExitStatus *int32                           `protobuf:"varint,6,opt,name=container_exit_status,json=containerExitStatus" json:"container_exit_status,omitempty"`
	CreationTime        *int64                           `protobuf:"varint,7,opt,name=creation_time,json=creationTime" json:"creation_time,omitempty"`
	NodeLabelExpression *string                          `protobuf:"bytes,8,opt,name=nodeLabelExpression" json:"nodeLabelExpression,omitempty"`
	XXX_unrecognized    []byte                           `json:"-"`
}

func (m *NMContainerStatusProto) Reset()                    { *m = NMContainerStatusProto{} }
func (m *NMContainerStatusProto) String() string            { return proto.CompactTextString(m) }
func (*NMContainerStatusProto) ProtoMessage()               {}
func (*NMContainerStatusProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{18} }

const Default_NMContainerStatusProto_Diagnostics string = "N/A"

func (m *NMContainerStatusProto) GetContainerId() *hadoop_yarn.ContainerIdProto {
	if m != nil {
		return m.ContainerId
	}
	return nil
}

func (m *NMContainerStatusProto) GetContainerState() hadoop_yarn.ContainerStateProto {
	if m != nil && m.ContainerState != nil {
		return *m.ContainerState
	}
	return hadoop_yarn.ContainerStateProto_C_NEW
}

func (m *NMContainerStatusProto) GetResource() *hadoop_yarn.ResourceProto {
	if m != nil {
		return m.Resource
	}
	return nil
}

func (m *NMContainerStatusProto) GetPriority() *hadoop_yarn.PriorityProto {
	if m != nil {
		return m.Priority
	}
	return nil
}

func (m *NMContainerStatusProto) GetDiagnostics() string {
	if m != nil && m.Diagnostics != nil {
		return *m.Diagnostics
	}
	return Default_NMContainerStatusProto_Diagnostics
}

func (m *NMContainerStatusProto) GetContainerExitStatus() int32 {
	if m != nil && m.ContainerExitStatus != nil {
		return *m.ContainerExitStatus
	}
	return 0
}

func (m *NMContainerStatusProto) GetCreationTime() int64 {
	if m != nil && m.CreationTime != nil {
		return *m.CreationTime
	}
	return 0
}

func (m *NMContainerStatusProto) GetNodeLabelExpression() string {
	if m != nil && m.NodeLabelExpression != nil {
		return *m.NodeLabelExpression
	}
	return ""
}

type SCMUploaderNotifyRequestProto struct {
	ResourceKey      *string `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey" json:"resource_key,omitempty"`
	Filename         *string `protobuf:"bytes,2,opt,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCMUploaderNotifyRequestProto) Reset()                    { *m = SCMUploaderNotifyRequestProto{} }
func (m *SCMUploaderNotifyRequestProto) String() string            { return proto.CompactTextString(m) }
func (*SCMUploaderNotifyRequestProto) ProtoMessage()               {}
func (*SCMUploaderNotifyRequestProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{19} }

func (m *SCMUploaderNotifyRequestProto) GetResourceKey() string {
	if m != nil && m.ResourceKey != nil {
		return *m.ResourceKey
	}
	return ""
}

func (m *SCMUploaderNotifyRequestProto) GetFilename() string {
	if m != nil && m.Filename != nil {
		return *m.Filename
	}
	return ""
}

type SCMUploaderNotifyResponseProto struct {
	Accepted         *bool  `protobuf:"varint,1,opt,name=accepted" json:"accepted,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCMUploaderNotifyResponseProto) Reset()                    { *m = SCMUploaderNotifyResponseProto{} }
func (m *SCMUploaderNotifyResponseProto) String() string            { return proto.CompactTextString(m) }
func (*SCMUploaderNotifyResponseProto) ProtoMessage()               {}
func (*SCMUploaderNotifyResponseProto) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{20} }

func (m *SCMUploaderNotifyResponseProto) GetAccepted() bool {
	if m != nil && m.Accepted != nil {
		return *m.Accepted
	}
	return false
}

type SCMUploaderCanUploadRequestProto struct {
	ResourceKey      *string `protobuf:"bytes,1,opt,name=resource_key,json=resourceKey" json:"resource_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SCMUploaderCanUploadRequestProto) Reset()         { *m = SCMUploaderCanUploadRequestProto{} }
func (m *SCMUploaderCanUploadRequestProto) String() string { return proto.CompactTextString(m) }
func (*SCMUploaderCanUploadRequestProto) ProtoMessage()    {}
func (*SCMUploaderCanUploadRequestProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{21}
}

func (m *SCMUploaderCanUploadRequestProto) GetResourceKey() string {
	if m != nil && m.ResourceKey != nil {
		return *m.ResourceKey
	}
	return ""
}

type SCMUploaderCanUploadResponseProto struct {
	Uploadable       *bool  `protobuf:"varint,1,opt,name=uploadable" json:"uploadable,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SCMUploaderCanUploadResponseProto) Reset()         { *m = SCMUploaderCanUploadResponseProto{} }
func (m *SCMUploaderCanUploadResponseProto) String() string { return proto.CompactTextString(m) }
func (*SCMUploaderCanUploadResponseProto) ProtoMessage()    {}
func (*SCMUploaderCanUploadResponseProto) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{22}
}

func (m *SCMUploaderCanUploadResponseProto) GetUploadable() bool {
	if m != nil && m.Uploadable != nil {
		return *m.Uploadable
	}
	return false
}

func init() {
	proto.RegisterType((*DistSchedRegisterResponseProto)(nil), "hadoop.yarn.DistSchedRegisterResponseProto")
	proto.RegisterType((*DistSchedAllocateResponseProto)(nil), "hadoop.yarn.DistSchedAllocateResponseProto")
	proto.RegisterType((*DistSchedAllocateRequestProto)(nil), "hadoop.yarn.DistSchedAllocateRequestProto")
	proto.RegisterType((*NodeLabelsProto)(nil), "hadoop.yarn.NodeLabelsProto")
	proto.RegisterType((*RegisterNodeManagerRequestProto)(nil), "hadoop.yarn.RegisterNodeManagerRequestProto")
	proto.RegisterType((*RegisterNodeManagerResponseProto)(nil), "hadoop.yarn.RegisterNodeManagerResponseProto")
	proto.RegisterType((*UnRegisterNodeManagerRequestProto)(nil), "hadoop.yarn.UnRegisterNodeManagerRequestProto")
	proto.RegisterType((*UnRegisterNodeManagerResponseProto)(nil), "hadoop.yarn.UnRegisterNodeManagerResponseProto")
	proto.RegisterType((*NodeHeartbeatRequestProto)(nil), "hadoop.yarn.NodeHeartbeatRequestProto")
	proto.RegisterType((*LogAggregationReportProto)(nil), "hadoop.yarn.LogAggregationReportProto")
	proto.RegisterType((*NodeHeartbeatResponseProto)(nil), "hadoop.yarn.NodeHeartbeatResponseProto")
	proto.RegisterType((*ContainerQueuingLimitProto)(nil), "hadoop.yarn.ContainerQueuingLimitProto")
	proto.RegisterType((*SystemCredentialsForAppsProto)(nil), "hadoop.yarn.SystemCredentialsForAppsProto")
	proto.RegisterType((*AppCollectorsMapProto)(nil), "hadoop.yarn.AppCollectorsMapProto")
	proto.RegisterType((*ReportNewCollectorInfoRequestProto)(nil), "hadoop.yarn.ReportNewCollectorInfoRequestProto")
	proto.RegisterType((*ReportNewCollectorInfoResponseProto)(nil), "hadoop.yarn.ReportNewCollectorInfoResponseProto")
	proto.RegisterType((*GetTimelineCollectorContextRequestProto)(nil), "hadoop.yarn.GetTimelineCollectorContextRequestProto")
	proto.RegisterType((*GetTimelineCollectorContextResponseProto)(nil), "hadoop.yarn.GetTimelineCollectorContextResponseProto")
	proto.RegisterType((*NMContainerStatusProto)(nil), "hadoop.yarn.NMContainerStatusProto")
	proto.RegisterType((*SCMUploaderNotifyRequestProto)(nil), "hadoop.yarn.SCMUploaderNotifyRequestProto")
	proto.RegisterType((*SCMUploaderNotifyResponseProto)(nil), "hadoop.yarn.SCMUploaderNotifyResponseProto")
	proto.RegisterType((*SCMUploaderCanUploadRequestProto)(nil), "hadoop.yarn.SCMUploaderCanUploadRequestProto")
	proto.RegisterType((*SCMUploaderCanUploadResponseProto)(nil), "hadoop.yarn.SCMUploaderCanUploadResponseProto")
}

func init() { proto.RegisterFile("yarn_server_common_service_protos.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1826 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x58, 0xcd, 0x72, 0xdb, 0xc8,
	0x11, 0x2e, 0x8a, 0x96, 0x4c, 0xb5, 0x64, 0x99, 0x1a, 0x53, 0x36, 0x25, 0xdb, 0x12, 0x0d, 0xc7,
	0xb1, 0x6a, 0x2b, 0xa5, 0x4d, 0x36, 0x7f, 0x55, 0x9b, 0x4d, 0x55, 0x24, 0xae, 0x9c, 0x30, 0x2b,
	0x32, 0x36, 0xe4, 0xdd, 0x4d, 0x52, 0xa9, 0xc5, 0x8e, 0xc0, 0x11, 0x85, 0x32, 0x30, 0x40, 0x00,
	0xd0, 0x16, 0x73, 0xc9, 0x25, 0x87, 0x3c, 0x46, 0xaa, 0x72, 0x4e, 0xe5, 0x09, 0x72, 0xce, 0x8b,
	0xe4, 0x90, 0x47, 0xc8, 0x31, 0x3d, 0x83, 0x01, 0x30, 0x43, 0x82, 0x12, 0xe5, 0xdd, 0x93, 0x84,
	0xfe, 0x9b, 0x9e, 0x9e, 0x6f, 0xbe, 0xee, 0x21, 0x3c, 0x9f, 0xd0, 0x98, 0x3b, 0x09, 0x8b, 0xdf,
	0xb2, 0xd8, 0x71, 0xc3, 0x20, 0x08, 0xb3, 0x2f, 0xcf, 0x65, 0x4e, 0x14, 0x87, 0x69, 0x98, 0x1c,
	0xc8, 0x3f, 0x64, 0xed, 0x82, 0x0e, 0xc3, 0x30, 0x3a, 0x10, 0xf6, 0x3b, 0x9b, 0xd2, 0x4b, 0xd7,
	0xef, 0xec, 0x55, 0x04, 0x32, 0x0c, 0xb6, 0x0b, 0x83, 0xe9, 0xd8, 0xd6, 0x3f, 0x6f, 0xc1, 0xee,
	0xa7, 0x5e, 0x92, 0x9e, 0xba, 0x17, 0x6c, 0x68, 0xb3, 0x11, 0xfe, 0xcb, 0x62, 0x9b, 0x25, 0x51,
	0xc8, 0x13, 0xf6, 0x52, 0x2e, 0xff, 0x35, 0x6c, 0xc6, 0x4a, 0xe1, 0xc4, 0x4a, 0xd3, 0xae, 0x75,
	0x6a, 0xfb, 0x6b, 0x1f, 0xfd, 0xf0, 0x40, 0x4b, 0xed, 0x20, 0x77, 0x3f, 0x8c, 0x22, 0xdf, 0x73,
	0x69, 0xea, 0x85, 0xbc, 0x4f, 0x67, 0xe2, 0xd9, 0xcd, 0x78, 0x6a, 0x19, 0x72, 0x02, 0xad, 0x80,
	0x5e, 0x3a, 0xd4, 0xf7, 0x43, 0xd7, 0x71, 0x69, 0x44, 0xcf, 0x3c, 0xdf, 0x4b, 0x27, 0xed, 0x25,
	0xb9, 0xc8, 0xce, 0xd4, 0x22, 0x49, 0x38, 0x8e, 0x5d, 0x15, 0x8b, 0xa0, 0xdf, 0xa1, 0x70, 0xeb,
	0x16, 0x5e, 0x32, 0x9a, 0xc7, 0x67, 0xa3, 0xd5, 0x17, 0x88, 0xe6, 0xf1, 0xe9, 0x68, 0x03, 0xd8,
	0xf2, 0xb8, 0x1b, 0xcf, 0x86, 0xbb, 0x75, 0x6d, 0xb8, 0x7b, 0xc2, 0x71, 0x3a, 0xde, 0x31, 0xec,
	0xb9, 0x21, 0x4f, 0xa9, 0xc7, 0xb1, 0x9c, 0x69, 0xf8, 0x86, 0x71, 0x87, 0x5d, 0x46, 0x5e, 0x3c,
	0x71, 0x3c, 0x8e, 0x35, 0x79, 0x4b, 0xfd, 0xf6, 0x32, 0x46, 0x5e, 0xb6, 0x1f, 0x15, 0x66, 0xaf,
	0x85, 0xd5, 0xb1, 0x34, 0xea, 0x29, 0x1b, 0xf2, 0x3d, 0x20, 0x65, 0x18, 0x6f, 0xe8, 0x24, 0x29,
	0x8d, 0xd3, 0xf6, 0x0a, 0x7a, 0xd6, 0xed, 0x66, 0xa1, 0xe9, 0x0d, 0x4f, 0x85, 0x9c, 0xfc, 0x1a,
	0x5a, 0x3c, 0x1c, 0xb2, 0xc4, 0x39, 0x0f, 0x63, 0x27, 0x11, 0x47, 0x3d, 0xf6, 0x3d, 0x3e, 0x6a,
	0xdf, 0xee, 0xd4, 0x71, 0x0f, 0x6d, 0x63, 0x0f, 0x03, 0x34, 0xec, 0x0d, 0x55, 0x41, 0xa4, 0xd7,
	0x8b, 0x30, 0x3e, 0x2d, 0x7c, 0xac, 0x7f, 0xd5, 0x34, 0xc4, 0xc8, 0xdd, 0xd1, 0x94, 0x99, 0x88,
	0xf9, 0x0d, 0x6c, 0x52, 0xa5, 0x98, 0x46, 0x8c, 0x65, 0xac, 0x55, 0xe9, 0x6e, 0x37, 0xe9, 0x94,
	0x78, 0x6e, 0xfe, 0x4b, 0xef, 0x97, 0xff, 0xe3, 0x8a, 0xfc, 0xff, 0x38, 0x66, 0x49, 0x9a, 0xa5,
	0x7f, 0x02, 0x4d, 0x2d, 0x7d, 0xa9, 0x50, 0xd9, 0x3f, 0x99, 0x93, 0x7d, 0xe9, 0x6c, 0xdf, 0xa5,
	0xa6, 0x14, 0x01, 0xd4, 0xca, 0x45, 0x43, 0xa7, 0x38, 0x99, 0x44, 0xe5, 0xfe, 0xd0, 0x88, 0xd8,
	0xcd, 0xd5, 0x0a, 0x40, 0x85, 0x63, 0xa1, 0x48, 0xac, 0x01, 0xdc, 0x15, 0x5b, 0x3c, 0xa1, 0x67,
	0xcc, 0x4f, 0xb2, 0x84, 0x7f, 0x06, 0xc0, 0x0b, 0x11, 0xa6, 0x3a, 0x1b, 0xb8, 0xf0, 0xc8, 0x02,
	0x6b, 0xe6, 0xd6, 0x3f, 0xea, 0xb0, 0x97, 0xdf, 0x5c, 0x61, 0xd6, 0xa7, 0x9c, 0x8e, 0xc4, 0xe5,
	0xd4, 0x2a, 0xf2, 0x03, 0xb8, 0x2d, 0x3c, 0x10, 0x68, 0xaa, 0x10, 0xf3, 0x4b, 0xbe, 0xc2, 0xe5,
	0x07, 0x79, 0x08, 0xab, 0x17, 0x69, 0x1a, 0x39, 0x51, 0x88, 0xb8, 0xac, 0x4b, 0x44, 0x37, 0x84,
	0xe0, 0x25, 0x7e, 0x93, 0x9f, 0x40, 0x23, 0x56, 0x57, 0x65, 0x81, 0x7b, 0x54, 0xd8, 0x92, 0xc7,
	0xb8, 0xd1, 0xc0, 0x41, 0x9a, 0x4b, 0x90, 0x5b, 0xe4, 0x3d, 0x59, 0xb5, 0x57, 0x79, 0xf0, 0x45,
	0x26, 0x20, 0xb6, 0x7e, 0x29, 0xf0, 0x46, 0xa4, 0xe3, 0x84, 0x25, 0x78, 0x29, 0x44, 0x3d, 0x9e,
	0x9a, 0x19, 0xf7, 0x8b, 0x8a, 0x9e, 0x4a, 0xbb, 0x6c, 0xa5, 0x4d, 0xd7, 0x94, 0xb2, 0x84, 0xbc,
	0x82, 0x7b, 0xf1, 0x98, 0x73, 0x44, 0x8e, 0x46, 0x6b, 0x89, 0xba, 0x39, 0x7b, 0x26, 0x1e, 0x4a,
	0x83, 0xbc, 0x1a, 0x55, 0xbe, 0xe4, 0x13, 0xe3, 0xb8, 0x1a, 0x72, 0xff, 0x8f, 0xaa, 0x8f, 0x2b,
	0x99, 0x3d, 0xaf, 0xff, 0xd5, 0xa1, 0x53, 0x79, 0x5e, 0xfa, 0x0d, 0xfc, 0x2d, 0xec, 0x4c, 0xb3,
	0x4c, 0x20, 0xa9, 0xd8, 0x79, 0xc3, 0x26, 0xea, 0x0c, 0x4d, 0x84, 0x64, 0x4c, 0xfd, 0x19, 0x9b,
	0x64, 0x2b, 0x3e, 0x30, 0xd9, 0xa7, 0xd0, 0xe2, 0x55, 0xbc, 0x87, 0x47, 0x30, 0x13, 0x72, 0xe9,
	0xfa, 0x90, 0x4d, 0x1e, 0x4c, 0xc5, 0x52, 0x85, 0x38, 0x74, 0x45, 0x5d, 0x24, 0x48, 0x36, 0x2a,
	0x0a, 0x91, 0xa9, 0xb5, 0x42, 0x64, 0x02, 0xf2, 0x14, 0xee, 0xc4, 0x01, 0x42, 0x92, 0xf1, 0xd4,
	0x3b, 0xf7, 0x58, 0x2c, 0x91, 0x54, 0xb7, 0xd7, 0xe3, 0xa0, 0x57, 0xc8, 0xc8, 0x87, 0x70, 0x6f,
	0xe8, 0xd1, 0x11, 0x0f, 0x93, 0xd4, 0x73, 0x13, 0x27, 0x60, 0x49, 0x82, 0xd5, 0x52, 0xd0, 0x21,
	0x9a, 0xaa, 0x9f, 0x69, 0x04, 0xc4, 0xe2, 0x12, 0x62, 0x2b, 0x19, 0xc4, 0xe2, 0x02, 0x62, 0x5d,
	0xd8, 0xa6, 0x31, 0x2b, 0xcf, 0xe7, 0xd0, 0x75, 0x59, 0x84, 0x17, 0xf4, 0x68, 0x62, 0xf7, 0x11,
	0x14, 0xb5, 0xfd, 0xc6, 0xc7, 0xcb, 0xe7, 0xd4, 0x4f, 0x98, 0x3d, 0xdf, 0xce, 0x80, 0x7f, 0x63,
	0x71, 0xf8, 0x5b, 0x5f, 0xc0, 0x93, 0xcf, 0xf9, 0xb7, 0x7f, 0x57, 0xad, 0xef, 0x80, 0x35, 0x27,
	0xae, 0x86, 0x29, 0x31, 0x2a, 0x6c, 0x0b, 0xe5, 0xaf, 0x18, 0xb6, 0x94, 0x33, 0x46, 0x53, 0x63,
	0xd9, 0x9f, 0xc3, 0x9a, 0x5c, 0x36, 0xbb, 0x76, 0x6a, 0xe9, 0xd9, 0xc3, 0xd4, 0x6f, 0x9b, 0x3c,
	0xcc, 0x4c, 0x40, 0x7c, 0x78, 0xe6, 0x23, 0x2e, 0x9c, 0x37, 0x3c, 0x7c, 0xc7, 0x9d, 0x2b, 0xb0,
	0xbb, 0x00, 0xd0, 0x3a, 0x22, 0xd2, 0x67, 0x22, 0x50, 0x77, 0x0e, 0x88, 0xbf, 0x82, 0x5d, 0x6d,
	0xb5, 0x2a, 0x3c, 0xd7, 0xaf, 0x5f, 0x66, 0xbb, 0x58, 0x66, 0x30, 0x07, 0xd8, 0xea, 0x86, 0xdf,
	0xba, 0xd9, 0x0d, 0x27, 0x1c, 0x3a, 0x7e, 0x38, 0x72, 0xe8, 0x68, 0x84, 0x93, 0x92, 0xe4, 0x0c,
	0x6c, 0x43, 0x82, 0x47, 0xb3, 0xfe, 0x47, 0xa3, 0x28, 0x41, 0x00, 0x0b, 0xfe, 0xf9, 0xae, 0x11,
	0xf3, 0x24, 0x1c, 0x1d, 0x96, 0x3e, 0xb6, 0x74, 0xc9, 0xa2, 0x3f, 0xf2, 0x2b, 0x54, 0xa2, 0x2f,
	0x22, 0x2f, 0x25, 0xe4, 0x4b, 0xd8, 0xca, 0x47, 0x32, 0xd9, 0xa2, 0x7c, 0x9f, 0xb9, 0x69, 0x18,
	0xe7, 0xcc, 0x69, 0x4d, 0x93, 0x5c, 0xb7, 0xb0, 0xe8, 0xd3, 0x28, 0x5b, 0xa0, 0x55, 0x06, 0x28,
	0xb5, 0xd6, 0x7f, 0x6b, 0xb0, 0x3d, 0x37, 0x29, 0xf2, 0x02, 0x36, 0x68, 0x49, 0x8b, 0x25, 0x5e,
	0xaf, 0x25, 0xd5, 0x3b, 0x54, 0x97, 0x91, 0x3f, 0xc0, 0xfd, 0xe9, 0x72, 0x29, 0x10, 0x2e, 0x49,
	0x46, 0xb9, 0xaa, 0x48, 0x3a, 0x1c, 0x5b, 0x7e, 0x85, 0x8a, 0x3c, 0x83, 0x35, 0x8d, 0x25, 0x24,
	0x2e, 0x56, 0x3f, 0xae, 0x0f, 0x3e, 0x3c, 0xb4, 0x75, 0xb9, 0xf5, 0x9f, 0x55, 0xd8, 0x99, 0xba,
	0x1c, 0x3a, 0x1f, 0xef, 0xc1, 0x5a, 0x3e, 0x08, 0xe5, 0x1b, 0x5d, 0xb6, 0x21, 0x17, 0xe1, 0x26,
	0xae, 0x26, 0xec, 0xa5, 0x6f, 0x9f, 0xb0, 0xeb, 0xdf, 0x9c, 0xb0, 0x6f, 0xdd, 0x90, 0xb0, 0x5f,
	0xc1, 0x56, 0x39, 0xff, 0x60, 0x46, 0x8e, 0xeb, 0x33, 0xca, 0xc7, 0x91, 0x02, 0xf3, 0xe3, 0xea,
	0x51, 0xa8, 0x68, 0xa5, 0xa5, 0xef, 0xeb, 0xb0, 0x9b, 0x79, 0x22, 0x74, 0x1f, 0x68, 0x60, 0x30,
	0x82, 0xae, 0x2c, 0xd6, 0xa1, 0xb7, 0x74, 0xff, 0x32, 0xf0, 0x8f, 0x60, 0x8b, 0xb3, 0xcb, 0x54,
	0x1e, 0xe7, 0x11, 0x1e, 0x67, 0x3e, 0x78, 0x4b, 0x8e, 0xaf, 0xdb, 0xd5, 0xca, 0x79, 0xdd, 0xa6,
	0x31, 0xb7, 0xdb, 0x0c, 0xa1, 0x63, 0x96, 0xe4, 0x4c, 0x8c, 0x9c, 0x41, 0xf8, 0x16, 0x2f, 0xe2,
	0x79, 0x1c, 0x06, 0xc8, 0x4d, 0xed, 0xd5, 0x45, 0xaa, 0xf3, 0x50, 0xaf, 0xce, 0x11, 0x0e, 0x9f,
	0x32, 0xc6, 0x0b, 0x0c, 0x31, 0x08, 0x88, 0x07, 0x0f, 0x93, 0x09, 0x9e, 0x61, 0xe0, 0xb8, 0x78,
	0x41, 0x45, 0x6f, 0xc4, 0x0e, 0x55, 0x72, 0x09, 0xc8, 0x05, 0x3e, 0x30, 0x16, 0x38, 0x95, 0xf6,
	0xdd, 0xd2, 0x5c, 0x91, 0x45, 0xb6, 0x5a, 0x3b, 0x99, 0xa3, 0xbe, 0xba, 0x3f, 0xae, 0x2d, 0xd8,
	0x1f, 0x5f, 0xc1, 0x7d, 0xb3, 0x2a, 0x43, 0x86, 0x89, 0x53, 0x7c, 0x44, 0xac, 0x5f, 0x3f, 0x34,
	0xb7, 0xf4, 0x4a, 0x7c, 0xaa, 0x1c, 0xc9, 0xef, 0xa1, 0x65, 0x86, 0x4c, 0xbc, 0x11, 0xc7, 0xe3,
	0xbc, 0x23, 0x03, 0xee, 0x9b, 0x7b, 0x97, 0xaa, 0x22, 0xac, 0x31, 0xde, 0x13, 0x3d, 0x7a, 0x66,
	0x68, 0xb4, 0xf3, 0x8d, 0x1b, 0x4c, 0xb3, 0x0e, 0x94, 0x97, 0xd6, 0xc1, 0x35, 0xc6, 0x38, 0x28,
	0x3a, 0xbe, 0x17, 0x78, 0x69, 0xfb, 0xae, 0x0c, 0xf3, 0xbc, 0x7a, 0x9f, 0xaf, 0x32, 0xd3, 0x13,
	0x61, 0xa9, 0x40, 0xec, 0x56, 0xe9, 0xc8, 0x4b, 0x20, 0x78, 0xc0, 0x1a, 0xa3, 0x23, 0x01, 0x44,
	0xed, 0xe6, 0xc2, 0xac, 0xde, 0xa4, 0x53, 0x62, 0xeb, 0xcf, 0xb0, 0x33, 0x3f, 0x0d, 0xb2, 0x0f,
	0x4d, 0xf1, 0x8e, 0x17, 0x5b, 0x61, 0x8e, 0xcf, 0xf8, 0x28, 0xbd, 0x50, 0x54, 0xb7, 0x81, 0x72,
	0x61, 0xcf, 0x4e, 0xa4, 0x94, 0xfc, 0x14, 0xb6, 0x4b, 0xcb, 0x77, 0xd4, 0x4b, 0x9d, 0xd4, 0x0b,
	0x90, 0x1a, 0x91, 0xa2, 0x32, 0xda, 0x5e, 0xb6, 0x5b, 0xb9, 0xcb, 0x97, 0xa8, 0x7e, 0x8d, 0xda,
	0x1e, 0xef, 0x27, 0xd6, 0x5f, 0xf0, 0xf5, 0x76, 0x25, 0x36, 0xc9, 0x8f, 0x61, 0x19, 0xd3, 0xee,
	0x2d, 0xdc, 0x4d, 0x32, 0x6b, 0x7c, 0x50, 0x6f, 0xba, 0xd3, 0x11, 0x65, 0x26, 0xeb, 0xf6, 0xac,
	0xc2, 0xfa, 0x13, 0x6c, 0x55, 0x96, 0xec, 0x7d, 0x57, 0xff, 0x00, 0x8c, 0x5a, 0x1f, 0x0e, 0x87,
	0xb1, 0x5c, 0x7c, 0xd5, 0x9e, 0x91, 0x5b, 0x21, 0x58, 0x59, 0x1b, 0x1d, 0xb0, 0x77, 0x85, 0xa6,
	0xc7, 0xcf, 0x43, 0x63, 0x1e, 0xeb, 0xc9, 0xee, 0xaa, 0x77, 0xf3, 0xda, 0xc2, 0xe7, 0x7e, 0xc7,
	0x38, 0x77, 0xeb, 0x19, 0x3c, 0x9d, 0xb7, 0xa0, 0x3e, 0x1f, 0x7e, 0x0d, 0xcf, 0x7f, 0xc9, 0xe4,
	0x49, 0xe1, 0x3b, 0x9b, 0x15, 0x86, 0x02, 0x2f, 0x48, 0x96, 0x46, 0x72, 0xef, 0x57, 0x25, 0xeb,
	0xef, 0x35, 0xd8, 0xbf, 0x72, 0x09, 0xbd, 0xe5, 0x3e, 0x80, 0xdb, 0xf8, 0x80, 0x8b, 0xf3, 0x76,
	0xbb, 0x6a, 0xaf, 0x88, 0xcf, 0xec, 0x65, 0x7a, 0xee, 0x87, 0xef, 0x1c, 0x4e, 0x03, 0xa6, 0x8a,
	0xdc, 0x10, 0x82, 0x01, 0x7e, 0x93, 0x27, 0xb0, 0x2e, 0x95, 0xf9, 0x03, 0x40, 0xf6, 0x7b, 0x7b,
	0x4d, 0xc8, 0xf2, 0x27, 0xc0, 0x2e, 0xc8, 0x4f, 0x07, 0x9f, 0x76, 0x22, 0x78, 0xf6, 0xea, 0x90,
	0x21, 0xed, 0x31, 0x66, 0x6c, 0xfd, 0xbb, 0x0e, 0xf7, 0xab, 0xdf, 0x97, 0xe4, 0x17, 0xb0, 0xae,
	0xff, 0x6a, 0xa3, 0xb6, 0x7f, 0x0d, 0xb5, 0xaf, 0x69, 0x3f, 0xe7, 0xe0, 0xb1, 0xde, 0x35, 0x9f,
	0xb8, 0x4c, 0x4d, 0x39, 0x9d, 0xea, 0x20, 0x62, 0x75, 0x45, 0x3c, 0x1b, 0xc6, 0xe3, 0x96, 0x19,
	0xb4, 0x55, 0xbf, 0x01, 0x6d, 0xa1, 0x5f, 0x14, 0x7b, 0x61, 0x3c, 0xef, 0x47, 0xb0, 0x97, 0x4a,
	0xa9, 0xfc, 0x72, 0xdb, 0xe9, 0x49, 0x6a, 0xb9, 0x7a, 0x92, 0x22, 0x1f, 0x69, 0x53, 0x82, 0xc3,
	0x2e, 0x91, 0x1a, 0xd4, 0x34, 0xb7, 0x22, 0x69, 0xa1, 0x1c, 0x03, 0x8e, 0x51, 0xa7, 0x86, 0x34,
	0x7c, 0x0a, 0x0a, 0x9e, 0x97, 0xb3, 0x9f, 0x20, 0x12, 0xd5, 0xa5, 0xd7, 0x73, 0xa1, 0x40, 0x0c,
	0xf9, 0x3e, 0x0e, 0x42, 0x79, 0xbf, 0x39, 0xbe, 0x8c, 0x70, 0x3f, 0xf2, 0x84, 0xb3, 0xe6, 0x5c,
	0xa5, 0xb2, 0xbe, 0x42, 0xae, 0xe9, 0xf6, 0x3f, 0x8f, 0xfc, 0x90, 0x0e, 0xc5, 0xc3, 0x08, 0xdf,
	0x94, 0x13, 0x03, 0xc7, 0x88, 0x96, 0xbc, 0x2c, 0xc5, 0xc3, 0x1a, 0xd1, 0x92, 0xcb, 0xc4, 0xc8,
	0xb4, 0x03, 0x8d, 0x73, 0x0f, 0xb9, 0x50, 0x07, 0x9b, 0xfa, 0xb6, 0x3e, 0x81, 0xdd, 0x8a, 0xf8,
	0x3a, 0x88, 0xd1, 0x9b, 0xaa, 0xce, 0x28, 0x83, 0x37, 0xec, 0xe2, 0xdb, 0x3a, 0x86, 0x8e, 0xe6,
	0xdd, 0xa5, 0x3c, 0xfb, 0xf7, 0x86, 0x09, 0x5a, 0x5d, 0x78, 0x52, 0x1d, 0x46, 0xcf, 0x63, 0x17,
	0x60, 0x2c, 0xc5, 0xf4, 0xcc, 0x67, 0x2a, 0x13, 0x4d, 0x72, 0xd4, 0x85, 0x47, 0x61, 0x3c, 0x3a,
	0xa0, 0x11, 0x75, 0x2f, 0x98, 0x81, 0x06, 0xf9, 0x33, 0xf3, 0xd1, 0xe3, 0xdf, 0xe1, 0xff, 0xa7,
	0xf2, 0x17, 0xea, 0xae, 0xfc, 0x81, 0xfa, 0x34, 0xfb, 0x31, 0x5a, 0x46, 0x4f, 0xfe, 0x5a, 0xab,
	0xfd, 0xad, 0x56, 0xfb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x43, 0x3b, 0x5d, 0x11, 0x17,
	0x00, 0x00,
}
